== Selección del Diario de John Griffith

Ha estado en mi mente escribir algo a modo de diario, de mi vida, viajes y experiencias,
en los compasivos y misericordiosos tratos del Señor conmigo,
a través del curso de mi peregrinaje por este mundo.
Y en la medida que le plazca al Señor abrir mi entendimiento espero que
también se les proporcionen señales provechosas a algunos viajeros cansados,
que están buscando la ciudad que tiene fundamento, cuyo arquitecto y constructor es Dios.

Nací el 21 del quinto mes de 1713, en Radnorshire, Gales del Sur,
con el privilegio de tener padres que tenían la sustancia
de la verdadera religión en ellos,
y que estaban conscientemente preocupados por criar a sus hijos en el temor de Dios.
Creo que cuando tenía aproximadamente siete u ocho años,
fui favorecido con visitaciones del amor de Dios que derretían mi corazón,
y frecuentemente experimenté que Su nombre estaba en las asambleas de Su pueblo,
"`como un precioso ungüento derramado,`" por lo que mis deseos de asistir
a las reuniones de adoración divina eran en gran medida aumentados.
Porque aunque, al igual que el Samuel de la antigüedad,
yo todavía no estaba familiarizado con la voz de Dios,
y no entendía claramente la Fuente de esa preciosa consolación que sentía, aún así,
recuerdo bien,
que algo obraba poderosamente en mi tierna y débil mente a manera de oposición,
para privarme de aquel disfrute dulce y celestial.
Este poder opositor a menudo presentaba ante mi vista algunos deleites transitorios,
y llenaba mi mente de pensamientos vanos, improductivos, y a veces malvados y blasfemos,
todo lo cual era de gran aflicción para mí. Luego,
el que es mentiroso desde el principio,
me sugería que rindiéndome a esos pensamientos y despreocupándome
por completo de lo que pasaba por mi mente,
era la única manera de reponerme de tal intranquilidad.
Descubrí que la carne quería tranquilidad y para salvarse a sí misma se unió voluntariamente
a las tentaciones de Satanás. De esta manera obtuve una especie de tranquilidad presente,
pero a costo de complacer los deseos que acumulan ira para el día
de la ira y de la revelación de los justos juicios de Dios.

A pesar de la falsa tranquilidad ideada por el enemigo de mi alma, a medida que crecía,
con frecuencia sentía palpablemente que esta paz era perturbada y rota por la
consciencia de la ira de Dios que era revelada desde el cielo contra mi injusticia,
y cuando los castigos del Señor estaban sobre mí por el pecado,
a menudo experimentaba gran amargura de espíritu.
En esos momentos yo hacía pacto con el Señor, prometiéndole que enmendaría mis caminos,
pero como esas promesas eran hechas en mi propia voluntad pronto eran rotas,
y eso incrementaba el peso de mi horror y de mi angustia.
Sin embargo, le plació al Señor en Su infinita misericordia,
encontrarme y contender conmigo como en "`el valle de la decisión.`"^
footnote:[Joel 3:14]

Al escribir esto,
mi mente se conmueve grandemente con lástima y compasión hacia los jóvenes negligentes,
que por amor a vanidades insignificantes,
desatienden la misericordia del Señor hacia ellos
y quedan sujetos a gran angustia de mente.
El caso es todavía peor,
cuando por causa de repetida desobediencia y rebelión
contra la inmerecida gracia de Dios,
estos casi han sofocado al divino Testigo en sus propios corazones y continúan impunemente.
¡Ay, tarde o temprano llegará el momento de despertar,
lo cual golpeará estos corazones con horror y estupor! ¡Ojalá sea en misericordia!

Mis piadosos padres fueron muy cuidadosos en prevenir
que yo cayera en malas compañías. No obstante,
sin el conocimiento de ellos,
yo a menudo las hallaba y me unía a ellas en aquellas
vanidades que son inconvenientes para los jóvenes,
no quedándome atrás de ninguno de mis compañeros en la locura.
No obstante, en la calma del día, a menudo me sentía severamente reprendido, sí,
a veces incluso en medio de mi vanidad,
pero por ese entonces yo quería silenciar al Testigo puro
que se levantaba contra el mal en mi corazón. ¡Oh,
desde entonces he admirado con frecuencia y profunda reverencia y gratitud,
la paciencia de un Dios compasivo,
pues no me cortó cuando yo deliberadamente me resistía
a Su instrucción (la cual es el camino de vida),
debido a que quería vivir en los placeres vanos de este mundo que perece.

Cuando tenía casi trece años, un Amigo que había vivido por un tiempo en Pennsylvania,
estando en nuestra área y frecuentemente en nuestro hogar,
hizo buenos comentarios de ese lugar.
Y debido a que yo ya tenía dos tíos y una tía ahí,
algunos de los cuales habían escrito antes animándonos a mudarnos a Pennsylvania,
mi inclinación por ir se acrecentó. Mis padres (especialmente
mi padre) al principio estaban muy en contra de la idea,
pero yo estaba obstinadamente inclinado a ir.
Así que,
cuando mis padres vieron esto y que mi hermano mayor también se inclinaba a ir conmigo,
finalmente consintieron y obtuvieron un certificado de buena reputación entre los Amigos.
Había otra familia de Amigos que viajaba en el mismo
barco y fuimos entregados a su cuidado.
Así, en el año 1726, nos embarcamos en Midford-haven,
a bordo del Constantine Galley of Bristol,
e hicimos un viaje de unas ocho semanas de tierra a tierra.
Éramos alrededor de ochenta o noventa pasajeros, en general sanos,
entre quienes nacieron tres niños mientras estábamos
a bordo y nadie murió. Mi tío John Morgan,
que vivía a unas doce millas de la ciudad de Filadelfia,
al enterarse de nuestra llegada subió a bordo y nos llevó a su casa,
donde yo continué por un tiempo.
Y mi hermano, puesto que era tejedor,
se estableció con mi tía Mary Pennel y continuó con su oficio.

Alejarme del vigilante cuidado de mis padres,
me proporcionó grandes oportunidades de complacer la mente
vana en los tontos entretenimientos de este mundo transitorio,
hacia los cuales yo tenía una inclinación demasiado grande.
Pero tengo que decir lo siguiente,
a fin de alentar a los padres a ejercer sus piadosos
esfuerzos para la preservación de sus hijos:
Yo creo firmemente que el cuidado religioso que mis padres tuvieron sobre mí en mi juventud,
imprimió un gran temor sobre mi mente,
que (a través de la bendición de la divina providencia)
fue un gran medio para guardarme contra los males más obvios,
a pesar de haber tenido muchas oportunidades de ser
tragado por ellos después de que dejé mi hogar.
Espero conservar siempre un recuerdo grato y agradecido de esos piadosos cuidados,
cuando considere que apenas logré escapar de esas rocas
en las que muchos han naufrago y se han arruinado.

Después de mi llegada a América, fui visitado por el Señor en algunas ocasiones,
y hasta cierto punto,
despertado a una consciencia de mi condición perdida sin un Salvador; sin embargo,
no sucedió tan frecuentemente como cuando era más joven.
Por haberlo resistido a Él con frecuencia (¡oh, con mucha frecuencia!) y adrede,
mi gusto por los placeres mundanos se había vuelto muy fuerte,
y yo estaba muy indispuesto a rendirme al llamado de Cristo.
Yo podía alegar una gran cantidad de excusas, insistiendo entre otras cosas,
que todavía era joven y que era posible que viviera muchos años. También razonaba,
que aun cuando viviera livianamente por unos pocos años,
todavía podría llegar a ser religioso antes de lo que muchos otros lo habían hecho,
quienes se habían convertido en hombres ejemplares en sus días. Así pues,
para tranquilizarme por un tiempo,
tomé la determinación de volverme un hombre muy religioso y bueno en algún momento,
pero que no debía ser todavía.

Así, por causa de la densa oscuridad que había cubierto mi mente,
estaba persuadido por la sutileza de Satanás,
a correr el terrible riesgo de dejar para el futuro
el arrepentimiento y enmienda de vida,
sin tener la certeza de que vería la luz de un día más. Por tanto,
me volví aun peor y me endurecí más en el mal,
aunque todavía era preservado de lo que comúnmente se considera
la más obvia contaminación. Pues yo tenía miedo de decir una mentira,
excepto para adornar o exagerar un cuento o una historia agradable o alegre,
pensando que no era un gran crimen mentir en broma.
No recuerdo haber hecho nunca un juramento o pronunciado una maldición.
Ni tampoco fui persuadido a apartarme en mi conversación diaria,
de las reglas de mi educación con respecto al lenguaje sencillo.^
footnote:[Por aquella época se estaba poniendo de moda hablar
con personas importantes y ricas de un cierto modo,
a manera de adulación, y dirigirse a los pobres,
niños y personas menos importantes de otro modo.
Los primeros Amigos se adhirieron a lo que entonces se consideraba el
"`lenguaje sencillo,`" en lugar de mostrar preferencia al dirigirse a
las personas de cierto estatus social de manera halagadora.]
Durante todo ese tiempo yo guardé un carácter bastante justo entre los hombres,
porque nadie habría podido culparme de algo que se considerara escandaloso.
Mantuve mucho amor y respeto por aquellos que yo pensaba que eran verdaderamente religiosos,
especialmente aquellos ministros vivos y sólidos del Evangelio eterno.
Creo que tenía una mejor consciencia de sus espíritus
y obras de la que tenían algunos de mis compañeros,
y por tanto, temía despreciarlos o hablar desdeñosamente de ellos,
como algunos de mis asociados hacían. En este estado carnal y degenerado,
asistía de manera habitual a las reuniones del primer día,
y algunas veces a otras reuniones durante la semana,
cuando algunos ministros de lugares distantes venían a visitar la reunión de Abington,
a la cual yo pertenecía. Desgraciadamente,
dichas reuniones fueron de poca o ninguna utilidad,
porque la obra dispensada sobre mí (por el ministerio público
o de otra manera) era como agua derramada sobre una piedra,
que se escurre de inmediato sin penetrar.
Yo, en realidad, durante un tiempo estuve '`como zarza en el desierto,
sin saber cuándo viene el bien`' (Jeremías 17:6). Si en
algún momento la Semilla del reino de Dios cayó en mi corazón,
que era como el terreno junto al camino,
pronto fue quitada y muy rápidamente perdí su sabor.

Cuando llegué a los diecinueve años de edad,
fui (por la infinita misericordia que nunca debe ser olvidada)
visitado por el Señor de una manera extraordinaria.
Quiero ser específico hasta cierto punto, dado que este fue el feliz medio por el que Él,
en buena medida,
volvió mi mente de las vanidades perecederas de un mundo
incierto al Dios de todas las fieles misericordias.
Una noche, estando con varios de mis compañeros de vanidad,
y sin restricción alguna porque los jefes de familia no estaban en casa,
llevamos nuestra conversación vana y superficial, y actos imprudentes y rudos,
al más alto grado de perversa insensatez del que nunca antes había sido culpable,
en lo que supongo, actué como una especie de cabecilla.
Debido a esto,
sentí algunos afilados latigazos de consciencia cuando me fui a la cama aquella noche,
con el fuerte pensamiento en mi mente,
de que nosotros no habíamos sido puestos en este mundo para tal propósito,
o para pasar nuestro tiempo como se mencionó anteriormente.
Yo le di algunos indicios de estos sentimientos a mi compañero de habitación,
aunque esta convicción no llegó muy profundo, pues muy pronto me quedé dormido.

No había dormido mucho antes de que un mensajero me alarmara con la noticia de
que uno de mis alegres compañeros (quien estaba entonces en la casa conmigo,
y quien, creo, se había comportado mejor que nosotros), estaba muriendo.
Él deseaba que yo fuera inmediatamente, lo cual hice,
y me horroricé enormemente en mi mente ante los pensamientos
de la manera en que habíamos pasado la noche anterior,
y por el repentino golpe que le sobrevino a este pobre hombre.
Pero cuando llegué al lado de su cama y vi la terrible agonía en la que estaba,
mi horror se incrementó más allá de toda descripción,
pues ninguno de nosotros esperaba que pudiera vivir muchas horas.
De mi parte, yo estaba tan profundamente sumido en una ansiedad mental,
que parecía que todos los dolores y terrores del infierno se habían apoderado
de mí. Entonces tuve la plena seguridad de que no había liberación para mí,
y de que seguro moriría antes de que llegara la mañana por el peso de
la angustia que estaba sobre mí. Esto sucedió la noche del séptimo día,
y aunque el joven eventualmente se recuperó,
no estaba en condiciones de ser dejado solo el día siguiente,
y esto me impidió ir a la reunión.

¡Oh, cuán deseoso estaba de ir a la reunión,
porque para ese momento yo estaba completamente despierto al sentido de mi deber!
Pero pasó una semana antes de que se volviera a presentar la oportunidad,
y esa me pareció la semana más larga que alguna vez yo hubiera vivido.
¡Oh,
cuánto anhelaba presentarme delante del Señor en las asambleas de Su pueblo
y poder derramar mis clamores internos delante de Él,
en un estado de sincero arrepentimiento y profunda contrición de alma!
Porque a través de la efectiva operación de Su poder en mi corazón,
estaba en condiciones de hacerlo.
Entonces claramente vi que el arrepentimiento es don de Dios,
y que Su amor (con el que Él nos ha amado en Cristo
Jesús nuestro Señor) conduce a los pecadores a este.
Mi voluntad carnal estaba por el momento vencida y silenciada,
y estaba rendido y con toda la disposición mental
hacia los requerimientos del Señor. En realidad,
estaba dispuesto a desprenderme de cualquier cosa, sin importar cuán querida me fuera,
por el disfrute real y sustancial del Amado de mi alma; pues en cierto grado,
fui llevado a experimentar que Él había venido "`para juicio a este mundo;
para que los que no ven, vean, y los que ven, sean cegados.`"
Ya no podía considerar mis anteriores deleites con satisfacción. En lugar de eso,
tenía una gloriosa visión de la hermosa elevación del Monte Sión,
y volví mi rostro hacia él. Pues el gozo que fue puesto delante de mí,
me dispuso a soportar "`la cruz de Cristo y menospreciar la vergüenza,`"
y aunque me convertí en un asombro y espectáculo para mi anteriores compañeros,
no le presté mucha atención,
sabiendo que tenía una causa justa para ser así. Mi gran cambio los impresionó,
porque observé que no se atrevían a burlarse o a ridiculizarme de frente.

El joven que fue el instrumento en la divina mano para mi despertar,
junto con su hermano,
fueron grandemente alcanzados y profundamente afectados
por la maravillosa visitación antes mencionada,
y hubo un cambio muy visible en ellos por un tiempo.
Pero al igual que la semilla que cayó sobre pedregales,
se marchitaron y no fructificaron para Dios.

Cuando llegó el primer día de la semana me regocijé
grandemente porque podía ir a la reunión,
la cual resultó ser en verdad memorable.
Había dos Amigos públicos^
footnote:[El término "`Amigo público`" era usado por los primeros Cuáqueros,
para referirse a aquellos miembros de la Sociedad que frecuentemente participaban
en viajes y ministerio público visitando las diversas reuniones establecidas.
Esos ministros nunca recibieron dinero por los servicios en el cuerpo del Señor,
al estar convencidos de que debían dar gratuitamente lo que había recibido gratuitamente.],
extranjeros, que parecía que habían sido enviados ahí por mi causa,
pues la mayoría de lo que ellos pronunciaron parecía aplicable a mi estado.
Entonces,
en alguna medida experimenté la sustancia de lo que se pretendía con el
"`bautismo de agua para arrepentimiento,`" "`el lavamiento de agua por
la Palabra`" y ser "`nacido de agua y del Espíritu,`" todo lo cual sería
plenamente visto y claramente entendido por los profesantes del cristianismo,
si conocieran correctamente el "`evangelio de Cristo,
que es poder de Dios para salvación.`" Este poder, internamente revelado,
es lo único capaz de obrar ese cambio en ellos,
sin lo cual (dice nuestro Señor) nadie verá el reino de Dios.
¡Pero, ay, por ser carnales en sus mentes, una religión espiritual no les interesa!
Como dicen las Escrituras:
"`Pero el hombre natural no percibe las cosas que son del Espíritu de Dios,
porque para él son locura, y no las puede entender,
porque se han de discernir espiritualmente.`"
Debido a esto,
los que profesan de nombre el cristianismo se aferran firmemente a las señales y sombras,
mientras que descuidan la sustancia.
Ellos abogan por la continuidad de los tipos,
mientras que el Antitipo es poco considerado.
Pero cuando esta sustancia es experimentada,
todas las sombras y tipos se desvanecen y llegan a su fin,
como lo hicieron los tipos y figuras de la ley cuando Cristo, el antitipo,
llegó e introdujo Su dispensación, la cual es de una naturaleza completamente espiritual.

Esta administración del agua por la Palabra continuó
sobre mí de manera extraordinaria casi tres meses,
en los cuales hallé gran deleite, pues fue acompañada con dulzura celestial,
como bálsamo sanador para mi espíritu herido,
y mi corazón fue derretido delante del Señor como se derrite la cera ante del fuego.
Grande era mi placer en la lectura de las Sagradas Escrituras y de otros buenos libros,
y en aquel momento fui beneficiado al recibir mucho consuelo y de este modo mejora.
Pero esta dispensación tranquila y tierna tenía que darle paso a una más poderosa,
es decir, al bautismo con el Espíritu Santo y fuego,
para que la era fuera completamente purificada.
Y entonces,
la anterior dispensación del Señor hacia mi alma se asemejó más al bautismo de Juan
con agua para arrepentimiento (porque era la sustancia a la que este bautismo apuntaba),
a fin de prepararle el camino al Señor.

Bajo esta ardiente dispensación me sentí por un tiempo sumamente angustiado,
bajo la consciencia de la gran alteración del estado de mi mente,
pues en verdad me sentía abandonado por el Señor
y yo le atribuía la causa a algo en mí mismo.
Toda la ternura de antes se había ido y yo era como un terreno seco.
Sí, mis agonías eran tan grandes que cuando era de día deseaba que fuera de noche,
y cuando era de noche deseaba que fuera de día. En las reuniones de adoración,
donde anteriormente había disfrutado de la mayor satisfacción,
ahora estaba bajo un enorme peso de dolor y angustia, a tal grado incluso,
que por momentos escasamente podía abstenerme de llorar
en voz alta por mera agonía. Cuando la reunión terminaba,
a veces me adentraba en el bosque a una considerable distancia,
para sin ser escuchado por ningún mortal,
poder desahogar mi muy afligida alma con angustiosos lloros.

En este abatido estado de mente se le permitió al
gran adversario derramar torrentes de tentaciones.
Yo era acosado casi constantemente por malos pensamientos, lo que me afligía mucho,
y aunque estaba demasiado iluminado como para voluntariamente
permitir o unirme a esos pensamientos malvados y corruptos,
a menudo me juzgaba no ser suficientemente fervoroso
en la resistencia de estas y otras tentaciones.
¡Oh, cuán oscura y angustiante era la condición en la que estaba mi mente!
En realidad, en aquellos días yo estaba tremendamente débil,
y estoy persuadido de que el Señor en piadosa bondad,
miró misericordiosamente la sinceridad de mi intención al no señalar todos mis fallos,
o nunca habría podido permanecer delante de Él con algún grado de aceptación. Por casi
un año mis tentaciones fueron muy grandes y mi angustia de mente muy profunda,
tiempo durante el cual fui como un niño pequeño en cuanto
al entendimiento de la manera y obra de Dios sobre mí,
para mi redención. Sin embargo, Aquel que "`la caña cascada no quebrará,
y el pábilo que humea no apagará,
hasta que saque a victoria el juicio,`" mediante Su invisible poder
levantó mi cabeza por encima de las furiosas olas de tentación,
de tal manera, que el enemigo descubrió que no podía vencerme.
El Señor adiestró mis manos para la batalla y mis dedos para pelear bajo Su estandarte,
y a través de Su bendición y ayuda, encontré algún grado de victoria sobre la bestia;
es decir, esa parte en el hombre que tiene su vida en las satisfacciones carnales.

Entonces el falso profeta comenzó a obrar con señales y prodigios mentirosos,
con el fin de engañar mi débil e inexperto entendimiento.
Esta escrito que "`Satanás se disfraza como ángel de luz,`" y así lo descubrí,
al menos en apariencia.
Pues al percibir que yo estaba demasiado iluminado de arriba
como para ser fácilmente arrastrado a la carnalidad,
el enemigo de mi alma (que busca a quien devorar),
astutamente intentó mi destrucción de otra manera, estableciéndose a sí mismo,
encubierto de mí, como guía en el camino de la muerte al yo.
Pues en aquel momento yo estaba decidido, a través de la ayuda divina,
a llevar con cuidado mi cruz y a negarme a mí mismo,
en todas aquellas cosas que parecían inconsistentes con la voluntad divina.
Pero el sutil engañador,
tomando ventaja del ardor de mi mente por seguir adelante con este asunto tan necesario,
sugirió que sería más fácil obtener una completa victoria sobre el mal,
si yo me abstenía por un tiempo de algunas de las necesidades de la vida,
particularmente de comer y tomar mi descanso natural de sueño,
apenas lo justo para preservar la vida.
Además sugirió que yo debía mantener mis manos continuamente ocupadas en los negocios,
ya que la holgazanería es el semillero del vicio,
y no se tardó en exponer Escrituras y pasajes de otros libros para confirmar sus exigencias.
En aquel momento yo realmente creía que era la voz
de Cristo en mi mente la que me demandaba estas cosas,
y por lo tanto, me esforcé en ser fiel a ellas,
aún cuando mi fuerza natural disminuía y mi cuerpo se debilitaba
más. Yo me angustiaba mucho cuando en algún momento quedaba
corto de lo que entendía que era mi deber en estos aspectos.
Descubrí que aquel que requería este servicio era un señor duro,
porque aunque tenía poder para engañar, no podía darme fe para que yo venciera.

Mis perspectivas en aquellos días eran en realidad muy descorazonadoras,
y mi pobre y afligida alma estaba casi sumida en la desesperación. Mis amigos notaban
que yo estaba en una angustia poco común. La familia con la que vivía entonces,
no podía dejar de advertir mis salidas a deambular por los campos en la noche,
de mi gran abstinencia de comida y de la profunda
angustia que estaba legiblemente impresa en mi rostro,
aunque yo la disimulaba tanto como podía. Ellos temían (como
entendí más tarde) que yo atentara contra mí mismo.
Yo me había prohibido hablar de mi condición con alguien,
pues sentía que sería buscar alivio de afuera, algo muy impropio e indigno.

A pesar de todo esto,
al Dios de toda gracia (quien permitió que esta poco común
aflicción cayera sobre mí para probarme y no para destruirme),
en Su maravillosa bondad,
le plació mover el corazón de un ministro perteneciente a nuestra
reunión para que me visitara y abriera un camino para mi liberación.
Él cuidadosamente me preguntó con respecto a mi condición interior,
informándome que los Amigos estaban muy preocupados por mí,
dado que era muy obvio que estaba bajo una tentación poco común.
Al principio yo estaba muy indispuesto a revelarle mi estado,
pero al final él prevaleció y aprovechó la oportunidad para mostrarme
que yo estaba bajo un grave engaño de Satanás. Por este medio,
a través de la misericordia del Señor, fui liberado del malvado plan de mi enemigo,
el cual era, sin ninguna duda, destruir tanto el alma como el cuerpo.
Y así, en reverente agradecimiento, me regocijé en Su salvación. Entonces vi claramente,
que Satanás debe ser cuidadosamente evitado en sus apariciones religiosas,
pues nada en la religión puede ser aceptable para Dios,
salvo el producto genuino de Su infalible Espíritu,
inequívocamente escuchado y entendido por el oído del alma y del entendimiento renovado.
"`Mis ovejas,`" dijo Cristo,
"`oyen mi voz,`" y entonces comencé a experimentar el cumplimiento de esta promesa.
¡Bendito sea el Señor para siempre!

En esa época tuve muchas preciosas revelaciones de los misterios divinos,
y cuando leía las Sagradas Escrituras,
eran abiertas a mi entendimiento más allá de lo que alguna vez lo habían sido.
En realidad tenía gran consuelo,
y mi esperanza fue reavivada y mi fe muy fortalecida
por aquellas cosas que fueron escritas de antemano.
Estoy muy seguro, por cierta experiencia,
de que los misterios expresados en esos santos escritos
no pueden ser correctamente entendidos,
si no es por medio del mismo Espíritu que inspiró a los escritores de ellos.
Es por tanto una vana presunción del hombre caído y no regenerado,
intentar desentrañar los misterios celestiales por
medio de su sabiduría terrenal y aprendizaje humano.
El labio veraz Mismo ha dado a conocer,
que dichos misterios están escondidos del sabio y entendido de
este mundo y revelados a los humildes y dependientes bebés,
es decir,
a los que palpablemente experimentan que su suficiencia
en cada buena palabra y obra procede directamente de Dios,
de modo que Cristo les es hecho "`sabiduría, justificación,
santificación y redención.`" La falta de esta experiencia interna
y viva ha sido la causa y les ha abierto el camino a la gran apostasía,
tinieblas y error que se han extendido en la llamada cristiandad.
No hay forma de recuperarla,
excepto por medio de la sumisión humilde a Cristo internamente revelado,
y aprendiendo de Él la naturaleza de la verdadera religión,
quien es el gran Autor de la misma.
Estoy muy seguro de que el yo precipitado, activo e inventor debe ser negado,
abatido y echado en el polvo para siempre,
y que sólo el Señor debe ser exaltado en nuestros corazones,
antes de que podamos levantarnos con aprobación divina
en los varios deberes de la verdadera religión.

Vi que la luz divina que comenzó a brillar de mis tinieblas y me separó de ellas,
era la "`lumbrera mayor`" que fue dada para señorear el Día de la salvación de Dios,
y que el salvado por el Señor debe caminar cuidadosamente en esta luz,
en la que no hay riesgo de tropezar.
También vi que cuando al Señor, para probar mi fe y paciencia,
le placía en Su sabiduría retirar esta santa luz,
para que me sentara en las tinieblas y en la región de sombra de muerte por un tiempo,
donde no tenía un conocimiento claro de qué hacer, mi deber crucial era entonces,
permanecer quieto y esperar a mi Guía infalible.
Y cuando durante esos tiempos el yo se levantaba y se intranquilizaba,
debía ser llevado a la cruz para que fuera asesinado.
Por esta experiencia descubrí que yo no era nada y que Dios
era todas las cosas necesarias para el alma y el cuerpo,
y que si yo quería ser introducido a un estado de reconciliación perfecta con Él,
debía experimentar todas las cosas hechas nuevas.

Por ese tiempo vi a lo lejos el llamamiento a la obra del ministerio.
Por momentos,
mi mente estaba tan maravillosamente cubierta por el amor universal
de Dios hacia la humanidad en el glorioso evangelio de Su Hijo,
que pensaba que yo podía (en la fuerza de Su amor) rendirme
para gastarme y ser gastado en la reunión de almas a Él,
el gran Pastor de Israel.
En realidad,
por momentos sentía que podía levantar mi voz como
una trompeta y despertar a los habitantes de la tierra.
Pero pronto descubrí que todo eso era únicamente la preparación para esa importante obra,
y que yo no había recibido aún la comisión de ocuparme de ella.
Un temor y cuidado estaban sobre mi mente,
para que no me atreviera a entrar en esa solemne empresa sin un verdadero llamado,
porque me parecía enormemente peligroso hablar en el nombre del Señor,
sin una clara evidencia en la mente de que Él lo requería de mí, la cual,
yo estaba entonces plenamente convencido, que Él daría en Su propio tiempo,
si yo me rendía para esperarla.

A partir de ese momento, hasta que fui realmente llamado a la obra,
tuve con frecuencia (en especial en las reuniones
religiosas) revelaciones de pasajes de las Escrituras,
con operaciones vivas del poder divino en mi mente.
A veces venían con tanta energía,
que casi estaba listo a ofrecerles a otros lo que había en mi mente,
pero debido al santo temor que habitaba en mi corazón,
me esforzaba en pesar mi ofrenda en la infalible balanza del santuario,
y hallaba que era demasiado liviana para ser ofrecida.
Entonces le agradecía al Señor Su misericordiosa preservación,
al haberme permitido evitar que ofreciera el sacrificio de los necios.
Sin embargo,
cuando realmente llegó el momento en el que se me requirió divinamente que hablara,
la evidencia era tan indiscutiblemente clara que no había el menor espacio para la duda,
pero por temor y debilidad humana lo pospuse y no cedí a lo que Dios requería. Entonces,
¡oh,
cuán condenado me sentía! ¡La dulzura divina que
había cubierto mi mente en las reuniones fue retirada,
y fui dejado en un estado muy pobre y desconsolado!
Me apresuré a suplicar perdón y a pactar con el Señor,
que si a Él le placía favorecerme de nuevo de la misma forma,
yo me rendiría a Su demanda.
En la reunión del siguiente primer día de la semana,
el poder celestial nuevamente me cubrió de manera maravillosa,
y se me requirió que me arrodillara en súplica al Señor con unas pocas palabras.
Esta vez cedí en el pavor de Su poder, con temor y temblor, y después,
mi alma fue llenada de paz y gozo en el Espíritu Santo y pude cantar y
hacer una dulce melodía en mi corazón para el Señor. Por lo que recuerdo,
yo tenía veintiún años el día que entré a esta grande y solemne obra del ministerio,
el 21 del quinto mes de 1734.

Me he visto impulsado a hablar más detalladamente con respecto
a la manera en que entré a la obra del ministerio,
para que quede a manera de advertencia y apropiado aliento para otros.
Pues por lo que he observado,
tengo motivos para temer que algunos hayan tomado la obra
de preparación (como antes impliqué) como la cosa misma,
y hayan avanzado mucho para su propio daño y el de
los demás. Los tales producen fruto prematuro,
lo cual es muy peligroso y debe ser cuidadosamente evitado.
Nada es suficiente defensa para guardarnos de esto,
sino mantener el ojo fijo en el Señor (por la bendición divina),
y con mucho temor considerar cuán grande es para '`el polvo
y las cenizas`' hablar como instruye el apóstol Pedro:
"`Cada uno según el don que ha recibido, minístrelo a los otros,
como buenos administradores de la multiforme gracia de Dios.
Si alguno habla, hable conforme a las palabras de Dios; si alguno ministra,
ministre conforme al poder que Dios da.`"
El autor de la carta a los Hebreos dice: "`Y nadie toma para sí esta honra,
sino el que es llamado por Dios, como lo fue Aarón.`" De modo que,
sin importar lo que algunos puedan pretender o dónde quieran entrometerse,
a menos que hayan sido realmente llamados por Dios,
no tienen participación en ese honor que únicamente viene de Dios.

La iglesia de Cristo ha tenido suficientes problemas con los falsos ministros,
tanto en los tiempos primitivos como en los nuestros.
Esa excelente libertad del evangelio,
en la que todos aquellos que se sienten inspirados (sea
hombre o mujer) pueden hablar o profetizar uno por uno,
ha sido y sigue siendo abusada por los que falsamente pretenden inspiración divina.
Sin embargo, esta libertad debe ser cuidadosamente guardada,
y debemos hallar otros medios para remediar el abuso en este aspecto,
lo cual no sería difícil,
si de manera general los miembros fueran más espirituales
y gustaran correctamente las cosas que son de Dios.
Entonces las acciones presuntuosas y no santificadas en
el ministerio serían fácilmente contenidas y suprimidas,
para no perturbar la paz de la iglesia.
¡Pero lamentablemente, el caso es a menudo lo contrario,
como he observado en muchos lugares!

Tal ministerio estéril a menudo no se considera un problema,
siempre y cuando las palabras y doctrinas sean correctas
y no haya nada que culpar en la conducta del orador.
Pero aquí lo principal es ignorado, lo cual es,
la poderosa demostración del Santo Espíritu,
y a los pocos que están profundamente dolidos en el corazón por
este ministerio sin vida les resulta muy difícil corregirlos,
por falta de fuerza, especialmente cuando perciben la fuerza que hay contra ellos.
Pues a los profesantes ceremoniosos del cristianismo les encantan hablar,
en lugar de sentarse en silencio.
He observado que estos engañadores son todo boca o lengua,
y que no tienen oído para recibir instrucción; les encanta enseñar a otros,
pero es imposible enseñarlos a ellos.
Le pido a Dios que avive a Su pueblo y que levante nuestra Sociedad,
a una experiencia más viva de ese bendito poder que
nos reunió al principio para que fuéramos un pueblo.
De lo contrario,
me temo que este gran mal resultará ser cada vez más grande entre nosotros, a saber:
Profesión sin posesión.

No tuve la libertad de omitir un comentario sobre este asunto,
dado que estoy completamente convencido de que los miembros vivos de la iglesia de Cristo
gimen bajo la dolorosa consciencia de esta triste señal de una sociedad decadente.
¡Ojalá el Señor de los Espíritus oiga sus gemidos
y considere la angustia que sufren sus almas en secreto,
y obre por medio de Su poder invisible para el bien de Su propio nombre
y la liberación de ellos! ¡Qué el Señor vuelva a disciplinar nuestra Sión,
purgue su escoria, le quite su impureza y deseche su plata,
para que sus jueces puedan ser restaurados como al
principio y sus consoladores como eran antes! ¡Oh,
que muchos, tras haberse calzado sus pies con el apresto del evangelio de paz,
aparezcan todavía hermosos sobre las montañas! ¡Qué así sea, dice mi alma!

He hecho algunas menciones de cómo sucedió conmigo durante el tiempo
de preparación para la grande e importante obra del ministerio,
y también del peligro que corría de ser engañado, incluso,
cuando en algunas ocasiones tuve revelaciones correctas y sentí la virtud dulce y eficaz
del amor de Dios a través de Jesucristo hacia la humanidad (la cual es,
sin duda,
a veces palpablemente experimentada y disfrutada por cada seguidor
fiel de Cristo que no es llamado a la obra del ministerio).
En esos días yo estaba intranquilo por el peligro de ser
llevado al ministerio a través de la puerta equivocada,
y desde entonces he visto más claramente el peligro de esta y de otras sendas que habrían
llevado a otorgarles a otros lo que Dios me había dado para mi propia vida espiritual.
En realidad,
muchas son las sendas que sacan del estado humilde
y dependiente (el único en que hay seguridad),
para que tengamos una voluntad y un camino propios,
y que de esa manera seamos equipados y enriquecidos con mucha provisión. Pero
en la sinceridad de corazón y esfuerzo ferviente de conservar el ojo puro,
y por el vigilante cuidado de la divina providencia sobre mí,
el Día del Señor brilló sobre todos esos peligros,
y claramente vi y por experiencia conocí que mi suficiencia era de Dios.
Vi que debe haber una constante dependencia en el Señor,
para ser equipado y provisto directamente por Él
cada vez que deba ocuparme de este solemne servicio.

Ardientemente deseo que todos los que tengan la mínima
sospecha de ser llamados a la obra del ministerio,
habiten en el santo temor de la divina presencia y experimenten
sus propias voluntades totalmente sujetas a la voluntad divina,
a la espera de una inequívoca y clara certeza de lo que el Señor requiere,
no sólo al principio, al entrar en dicha obra, sino en todo momento.
Y en la medida que el yo llegue a ser puesto en el polvo,
así recibirán evidencia innegable en sus propias mentes de la certeza de su misión,
y el testimonio de confirmación del Testigo de Dios estará presente en
las consciencias de aquellos entre quienes son enviados a ministrar.
Los verdaderos ministros serán olor de vida para los que viven
en la Verdad y de muerte para los que están en el estado de muerte.
Que siempre sea recordado, que nada del hombre o que pertenezca a él,
tiene posibilidad de agregar algún brillo o dignidad al don divino.
Que sin el poder, luz y demostración del Espíritu de Cristo,
las mejores y más perfectamente compuestas palabras o doctrinas
(aunque sean muy ciertas y correctamente entregadas) no son más
que metal que resuena o címbalo que retiñe. Permítanme añadir,
que aquellos que consideran el poder del Señor como la sustancia de sus ministerios,
no tienen necesidad de preocuparse por las palabras,
ya que las más pequeñas y simples son realmente hermosas
cuando son habladas adecuadamente bajo la santa influencia.

Tras entrar al servicio solemne y serio del ministerio,
me dediqué mayormente a pronunciar unas pocas palabras de manera quebrantada,
con temor y temblor,
según lo requería la Verdad (a través de Su propio poder y eficacia
divinos) moviéndose en mi corazón y sometiendo mi voluntad.
El Señor fue sumamente misericordioso conmigo, tomándome de la mano como un padre tierno,
y disponiéndome mediante Su gran poder a ser contado
como un tonto por causa de Su nombre y la del evangelio.

La reunión a la que yo pertenecía entonces era grande
y tenía un cuerpo de Amigos valioso y de peso.
Hasta donde podía observar por el aspecto de ellos,
estos reconocían y aprobaban mis apariciones débiles y bajas en el ministerio.
Sin embargo,
utilizaron la prudencia cristiana de "`no imponer manos rápidamente
sobre mí,`" sino que me dieron plena oportunidad para dar prueba
de mi ministerio y para que me orientara en él.

Por este tiempo se levantó un buen brote de ministerio
dentro del área de nuestra Reunión Anual,
pues cerca de cien personas abrieron sus bocas con testimonio público por poco
más de un año. Varias de estas llegaron a ser ministros poderosos y capaces,
pero algunas se marchitaron como fruto inmaduro.
Durante ese tiempo,
cerca de diez fueron levantados como ministros y comenzaron
a predicar en la reunión específica de Abington,
a la cual yo pertenecía.

En la medida que esperaba que Dios incrementara mi capacidad de ministrar,
así experimentaba un considerable crecimiento y ensanchamiento,
y en el fiel cumplimiento de mi deber,
una gran paz y consuelo celestial fluían a mi alma como una plácida y refrescante corriente.
También descubrí que este era el medio de unirme aún más con los Amigos,
en una dulce y cómoda cercanía,
la cual nunca antes había sentido tan amplia y vívidamente.

Muchos jóvenes de buenas intenciones y algunos otros
de poca experiencia parecían admirar mi don,
y algunas veces hablaban muy bien de él,
aunque no siempre se abstenían de hacerlo fuera del alcance de mi oído. ¡Oh,
cuán peligroso es esto si los ministros lo disfrutan!
Puede ser justamente comparado con un veneno que en poco tiempo,
destruirá la vida pura e inocente.
Mi juicio estaba en contra,
pero encontré algo en mí que parecía estar más inclinado a escucharlo,
aunque no con total aprobación. Eso mismo en mí quería saber qué pensaban de
mí tales y cuales personas (aquellas que eran de mayor estima por experiencia
y sabiduría). A veces me imaginaba que me miraban con desconfianza,
lo cual me desanimaba.
Pero vi que todo esto, siendo que provenía de la raíz del yo, debía ser juzgado,
y supe que debía morir en la cruz antes de que yo estuviera en
condiciones de ser confiable con alguna medida del tesoro del evangelio.

Yo también me empecé a deleitar mucho en mi don,
y si la divina Bondad en Su misericordia no lo hubiera evitado (mediante un bautismo^
footnote:[Él usa la palabra bautismo de manera figurativa,
hablando de ser sumergido en ardientes experiencias,
pruebas y juicios por medios de los cuales el Señor '`limpiará Su era`' completamente.]
profundo y angustiante), le habría abierto una puerta al orgullo espiritual,
el peor tipo de orgullo, y habría entrado por ella para mi ruina.
Tengo razones para pensar que los Amigos experimentados,
al observar mi gran crecimiento y ensanchamiento de ramas en la parte alta,
temieron mi caída en caso de tormenta.
Sin embargo, en medio de mi vanidosa carrera,
le plació al Señor quitarme por un tiempo el don del ministerio,
junto con todo consuelo palpable de Su Espíritu,
de modo que quedé (según yo) en total oscuridad, es decir,
en la región y sombra de muerte.
En este abatido estado mental fui gravemente acosado y tentado por el falso profeta,
el que se transforma,
para que mantuviera mi crédito en el ministerio al continuar con mis servicios públicos.
Bien podría decirse que él "`hace descender fuego
del cielo a la tierra delante de los hombres,
y engaña a los moradores de la tierra`"; pues así descubrí que es.
¡Oh,
es difícil imaginar cuán cercana es la semejanza
que el enemigo puede lograr de las cosas de Dios,
o cuán exacta la imitación que puede hacer de las mismas!
De hecho, por el estado mental en el que me encontraba entonces,
en algunos momentos estuve dispuesto a decir: "`¡Ah,
veo y siento que el fuego del Señor desciende para preparar mi ofrenda!`"
Y cuando estaba casi listo a rendirme ante esta insinuación
y hablar en el nombre de Dios,
un piadoso temor se apoderaba de mi mente y sentía
el deseo de probar mi ofrenda de nuevo.
Por este medio fue descubierto el fuerte engaño en el que estaba,
el fuego falso fue rechazado y mi alma fue sumergida
en una ansiedad más profunda de la que había antes.

No hay lengua o pluma que pueda expresar plenamente la angustia casi constante
de alma que estuvo sobre mí por cerca de cuatro o cinco meses.
Con respecto a mis amigos, en alguna medida me sucedió como a Job;
algunos suponían que la causa de esta caída era una cosa y otros suponían otra,
aunque por la misericordia,
no podían culparme de ninguna mala conducta como la causa de la misma.
La razón más probable de mi cambio, en la mente de muchos,
era que yo había sido demasiado elogiado por otros y que por eso había perdido mi don.
De hecho, eso se acercó más a la verdad.
Sin embargo, no estaba completamente perdido,
porque cuando mi misericordioso Ayudador vio que mi sufrimiento era suficiente,
restauró el don otra vez y apareció en mi alma como una mañana clara sin nubes.
¡Alabanzas eternas a Su santo nombre!
Mi mente estaba profundamente inclinada en humilde gratitud,
bajo el sentido del gran favor de ser otra vez tenida
por digna de que se le confiara un don tan precioso.
Por tanto, yo tenía cuidado de ejercerlo con gran temor y temblor,
incluso con una cruz aun mayor sobre mi propia voluntad que antes.

En el curso de mi experiencia religiosa,
muy a menudo he tenido motivos para admirar y adorar
los tratos de la divina Sabiduría para conmigo,
con el fin de preservarme en el camino de paz.
Estoy muy seguro de que Él obrará así por toda aquella humanidad
que esté enteramente rendida de corazón a Él,
para que no sea posible que pierda la felicidad eterna.
Porque en verdad,
nadie es capaz de arrebatar de Su todopoderosa mano a los que no Lo abandonan primero.

Después de que había aparecido en el ministerio público poco más de dos años,
sentí que el evangelio de amor (según comprendí) me movía a visitar
las reuniones de Amigos en algunas lugares de Nueva Jersey.
Al ser joven en el ministerio,
por momentos tenía gran temor de equivocarme en lo que pensaba que Dios requería de
mí. Tenía pavor de correr cuando el Señor no lo deseaba y adonde Él no me había enviado,
y así traer deshonra a Su bendito nombre,
y exponerme a los Amigos sabios y con discernimiento,
como alguien sin las cualidades apropiadas para tan grande responsabilidad.
Mi angustia era grande, de noche y de día,
pidiéndole al Señor una mayor confirmación. Él escuchó
misericordiosamente mis clamores y le plació,
mediante un sueño o visión nocturna, proporcionarme tan plena satisfacción,
que no recuerdo haber tenido después ninguna duda al respecto.

Comencé el viaje el 7 del octavo mes de 1736, con un compañero mucho mayor que yo.
Visitamos las siguientes reuniones, a saber: Pilesgrove, Salem,
Alloways Creek y Cohansey, donde mi compañero me dejó y regresó a su hogar,
al sentirse desanimado en su propia mente acerca del viaje.
Sin embargo,
en la medida que yo descubría al Señor cerca mediante Su bendito poder
(abriendo mi boca y ensanchando mi corazón abundantemente en Su obra),
así era animado a proseguir,
acompañado en el viaje por un Amigo intachable que
pertenecía a la reunión de Alloways Creek,
quien tenía unas pocas palabras que decir en las reuniones.
Pasamos a través de un territorio deshabitado de aproximadamente cuarenta millas,
de Cohansey a Cape May,
donde tuvimos una reunión. De ahí fuimos llevados
a Great y Litlle Egg-harbor y tuvimos reuniones,
y luego, a través de lugares despoblados, a la Reunión Anual en Shrewsbury,
la cual fue grande y muy favorecida con la presencia divina.
Varios Amigos ministros de Pennsylvania estaban ahí: Thomas Chalkley, Robert Jordan,
John y Evan Evans, Margaret Preston y otros.

No era conveniente para mi crecimiento en el ministerio, ni para mi inclinación,
usar mucho tiempo predicando en esas grandes reuniones.
Por lo tanto, en su mayor parte,
les di paso a los que estaban mejor calificados para la obra, y que según mi estima,
eran dignos de doble honor.
Yo tenía un gran respeto en mi mente,
por todos aquellos que yo pensaba que eran pilares de la casa de Dios,
fueran ministros o ancianos.
Realmente creo que si alguno de ellos, según su discernimiento,
hubiera expresado que yo estaba equivocado en alguna de mis ofrendas, en algún momento,
probablemente habría dependido más de su juicio que del mío. Por
muchos años me consideré como un niño en cuanto a experiencia,
en todo sentido, y por tanto,
pensaba que la sujeción a aquellos que eran padres y madres de Israel era mi deber.
Nunca, que yo recuerde, ignoré a ninguno de ellos,
lo cual es ahora una gran satisfacción para mi mente.

Confieso que desde entonces,
en algunas ocasiones he tenido motivos para maravillarme del atrevimiento de algunos,
que aunque niños en el ministerio (si es que realmente son niños),
han emprendido la obra de los hombres,
demostrando apenas una disposición a darles preferencia
a los demás por encima de ellos mismos.
Y cuando estos han sido exhortados por los de mucho más experiencia que ellos,
han sido capaces de disputar o defender la comisión divina,
alegando que era correcto obedecer a Dios antes que al hombre,
como si tuvieran el derecho exclusivo de hablar y juzgar en el cuerpo.
Pero yo había visto muchas veces el gran peligro
de ser engañado y burlado por el que se transforma,
y por tanto, tenía temor de confiar en mi propia vista,
y consideré más seguro para mí permanecer muy abierto
a la instrucción y dejar que llegara de quien fuera,
pues no había nada más deseable para mí que estar en lo correcto.

Esta gran reunión en Shrewsbury terminó bien y dulcemente.
¡Alabanzas al Señor sobre todo para siempre!
De ahí fuimos a las reuniones en Chesterfield, Trenton, Bordentown, Mansfield,
Upper Springfield, Old Springfield, Burlington, Bristol, las Falls, Ancocas, Mount Holly,
Evesham, Chester, Haddonfield y Woodbury Creek, después de lo cual regresé a casa.
El Señor prosperó mi viaje y por momentos fue como una fuente incontenible,
proveyendo diariamente para la obra en la que Él me había involucrado.
En verdad, se mostró maravillosamente misericordioso hacia mi débil estado,
dando tanto sabiduría como palabras, tal como está escrito:
"`De la boca de los niños y de los que maman, fundaste la fortaleza.`"
¡Alabanzas a Su santo nombre por siempre!

Sin embargo,
aunque el Señor me había encomendado la comisión del evangelio
y se complacía en recompensar mis esfuerzos sinceros en la misma,
con dulces beneficios de paz y gozo en el Espíritu Santo,
y con la unidad de los hermanos en un grado cómodo, aún así mis tentaciones eran grandes,
y diversos los combates que tuve contra los enemigos
de mi alma durante algunos años. ¡Oh,
cuánto me costó evitar ser contaminado (en un grado u otro) debido a los casi
continuos ríos de inmundicia que salían de la boca del dragón! De hecho,
él buscaba arrastrar mi imaginación hacia diversos placeres ilícitos,
y de estos no siempre escapé por completo.
Algunas veces era persuadido a que estableciera límites por mí mismo,
y aunque no caía directamente en el mal que estaba tentado a hacer,
sí disfrutaba y me satisfacía acercarme tanto como pensaba que era lícito.
De esta manera,
por falta de vigilancia cuidadosa (no sólo para esquivar
lo que sabía que era en verdad malo,
sino también cada apariencia de mal),
en algunas ocasiones traje gran angustia y profunda aflicción sobre mi mente.
Y cuando me había salido un poquito del camino correcto,
encontraba que eran necesarios muchos (¡oh, sí,
muchos!) penosos pasos y dolorosas angustias,
antes de ser recibido de nuevo en el camino y favor de mi Padre celestial.

Desde entonces, he estado humildemente agradecido por Su preservación, es decir,
por guardarme fuera de los males más mortales,
considerando cuán peligrosamente los permití a veces en
mi imaginación. ¿Cómo pueden los débiles mortales determinar
hasta qué punto llegarán al cederle algo de terreno al mal?
En verdad, al buscar cualquier grado de placer en pensamientos de cosas prohibidas,
el hombre trabaja grandemente para su propio dolor.
He descubierto mediante lamentable experiencia,
que cuando se le da la menor oportunidad al enemigo, gana ventaja sobre nosotros,
y como resultado, somos enormemente debilitados.
Así,
en lugar de crecer "`como sauces junto a las riberas de las aguas,`" hay
peligro de que nos marchitemos y seamos como aquellos que retroceden,
en quienes el Señor no se agrada.
He descubierto que lo primero que hace Satanás sutilmente,
es sacarme del constante cuidado de llevar todos mis pensamientos,
palabras y actos a la luz de Cristo para que sean tratados por ella en mi propio corazón,
y en lugar de esto, que los examine por medio de mi razonamiento parcial.
Aquí muchas cosas realmente malas en su naturaleza o tendencia, o ambas,
pueden tener la apariencia de ser algo trivial, y entonces,
la mente alega que no hay nada malo en esta, aquella u otra cosa.
Y aunque haya dudas en la mente,
estas pueden ser razonadas en sentido opuesto (sin considerar debidamente,
que '`el que duda, es condenado.`') Así,
(¡ay!) cuando al Juez verdadero de todos le ha placido levantarse,
me ha hallado con mi cubierta de hoja de higuera,
tras haber perdido en gran medida el vestido de inocencia
y la santa confianza hacia Dios,
al darle paso a las cosas malas.
¡Oh, cuánto se ha calentado el horno por causa de mi negligencia,
a fin de que toda la escoria sea quitada!

Así sucedió conmigo,
hasta que las muchas disciplinas del Padre celestial me llevaron a más temor,
cuidado y sujeción. No podía dejar de mencionarles mis muchas debilidades y fallas,
para que otros aprendan a tener cuidado.
También creo que esta es la razón principal por la que Dios
nos ha trasmitido por medio de las Sagradas Escrituras,
los fallos y fracasos de Su pueblo.
¡Oh, ustedes viajeros a Sión, miren el gozo que está puesto delante de ustedes,
sin permitir que sus ojos vaguen alrededor,
para que no les trasmitan tal deleite a sus corazones
que pueda infectar sus almas con una enfermedad mortal,
debido a la cual no serán capaces de proseguir en su viaje a la ciudad santa!
Tengan cuidado de no cargarse con el fruto aparentemente
agradable de esa tierra por la que están pasando.
Aunque cuelgue abundantemente a cada lado,
no será útil para ustedes en la tierra celestial hacia la que van,
ni les servirá para un verdadero refrescamiento en el camino.
Si desean que el camino les sea prosperado, miren fijamente hacia adelante,
con el ojo puesto únicamente en el galardón. Lleven inmediatamente
a la cruz cada movimiento que busca satisfacción en lugares prohibido,
y pronto encontrarán que el yugo de Cristo es fácil y Su carga ligera.
En realidad, encontrarán todos Sus caminos placenteros y Su sendas pacíficas.
Esto es mucho mejor que esa intranquila e inconsistente manera de viajar:
pecando y arrepintiéndose, arrepintiéndose y volviendo a pecar,
lo cual sienta las bases para la murmuración,
esclavitud y afán. Estos claman (algunos todas sus vidas) que no se puede
obtener una completa victoria sobre el pecado en este lado de la tumba.
"`Debemos permanecer como miserables pecadores,`" dicen,
cuando la razón yace completamente en ellos mismos,
pues no quieren entrar ni permanecer en la ayuda del Señor
contra los poderosos enemigos de la felicidad de sus almas,
la cual es totalmente suficiente para dar completa victoria sobre todos ellos.
En verdad, Él es capaz de darnos poder para triunfar y decir,
"`somos más que vencedores por medio de aquel que nos amó.`"

[.asterism]
'''

__John Griffith fue ministro entre 1734 y 1776,
cerca de cien años después del gran derramamiento
de luz y poder que dio origen a la Sociedad de Amigos.
A pesar de que la Sociedad continuó creciendo en número a través de la mayor
parte de los 1700 (y un remanente vivo sobrevivió incluso hasta los 1800),
hubo un declive triste y constante de la verdadera vida y devoción,
después de los primeros cincuenta años de prosperidad y pureza.
John Griffith pasó toda su vida trabajando en medio de una iglesia en decadencia,
advirtiéndoles que no perdieran su primer amor, e insistiendo en la necesidad de la guía,
luz y poder del Espíritu en todas las cosas.
En una de las muchas expresiones halladas en su diario completo escribe:
"`Hace ya casi un siglo que el Señor, mediante Su brazo extendido,
reunió nuestra Sociedad a partir de las áridas montañas
y desoladas colinas de la profesión vacía,
escogiéndolos para Su propio y particular rebaño y familia,
como se mostraba plenamente por medio de muchas evidentes
señales de Su amor y poderosa protección;
aun cuando los poderes de la tierra, como las furiosas olas del mar,
se levantaban contra ellos con todo el propósito de esparcir y devastar.
Puede ser justamente preguntado:
¿Qué pudo haber hecho el Señor por nosotros que no haya hecho?
¡A pesar de lo cual, qué indiferencia,
tibieza e insensibilidad hacia la vida de la religión
son halladas ahora entre muchos bajo nuestro nombre!
Más aún, en algunos lugares este doloroso letargo ha llegado a ser casi general.`"__

__John Griffith junto con una fiel minoría en su generación,
derramaron sus vidas por las verdades del evangelio,
por la pureza de la iglesia y por la gloria del Señor en la tierra.
Murió por complicaciones de asma en 1776, a los 63 años de edad.__
