== Prefacio

Si no hubiera sentido que era mi deber ofrecerle a su seria lectura las
siguientes observaciones sencillas que he recibido por experiencia,
el lector no habría sabido de mí de esta manera.

A menudo, junto con muchos hermanos y hermanas en la Verdad,
me he sentido profundamente afectado al ver el gran peligro al que se
exponen los profesantes cristianos debido a la apatía espiritual.
Cuando un adormecedor letargo ha tomado dominio en el corazón del hombre,
entonces una religión basada en conceptos y especulaciones satisface su mente depravada.
Por esto,
no se busca una verdadera renovación del corazón
(sin la cual nadie puede ser verdaderamente religioso),
y los hombres, al estar satisfechos solamente con la cáscara o forma,
no son conscientes de que carecen de la sustancia.

Cuando el sutil adversario encuentra a los hombres en esta clase de sueño o estupefacción,
entonces ve que es su oportunidad para sembrar cizaña entre el trigo; y por este medio,
el campo de la iglesia cristiana se ha llenado de ella con el pasar del tiempo.
Lo que más ardía en mi corazón y me llamaba a ocuparme en esta publicación (además de
un anhelo ferviente de que sea de provecho eterno para los cristianos de todas las denominaciones),
era un deseo de que los descendientes de un pueblo que hace
poco más de un siglo fue sacado maravillosamente y redimido
de todas las sombras sin vida y formas de religión vacías,
para disfrutar y ser cimentados en el bendito poder y vida,
pudieran ser verdaderamente preservados en la experiencia del camino
y medio por el cual nuestros dignos predecesores obtuvieron un
establecimiento firme en la Verdad que está en Jesucristo;
porque es evidente que no es posible alcanzar el
fin cuando el único medio para alcanzarlo es descuidado.

Es una triste verdad, y demasiado obvia para ser negada,
que muchos de los descendientes de la antigua Sociedad de los Amigos,
en estos días de paz y abundancia externa,
teniendo sus corazones inclinados hacia la falsa libertad y comodidad,
eviten la cruz de Cristo que los crucificaría al mundo.
Y es en consideración a esto,
que siento la necesidad de presentarles algunas observaciones
adecuadas al estado actual de las cosas;
procurando (en cierto grado) ofrecer a la consideración
de las generaciones presentes y futuras,
el medio por el cual nuestros valiosos predecesores
se convirtieron en un cuerpo honorable y vivo,
con la esperanza de que se muestre claramente la necesidad de experimentar
el mismo bendito poder operando en sus corazones y mentes,
como lo único que puede capacitarlos a todos para seguir correctamente los pasos
de esos valientes hombres y mujeres en la defensa de la causa de Dios.

La objeción que me ha causado cierto desánimo les puede ocurrir también a algunos lectores,
a saber,
que los temas que se tocan en este pequeño tratado han sido muchas
veces juiciosamente escritos antes por diferentes autores;
pero lo mismo podría decirse de la mayoría de los temas religiosos.
La sabiduría y la misericordia divinas han visto la necesidad de
revivir las mismas verdades por medio de diferentes instrumentos,
de generación en generación; y así los siervos del Señor han hablado una misma cosa,
como si proviniera de una sola boca.
Aquí es muy notable la misericordia y condescendencia
de Dios para con la fragilidad humana,
al hacer que esas excelentes verdades,
tan esenciales para la salvación del alma del hombre,
sean frecuentemente revividas e inculcadas,
sabiendo que el hombre es tan propenso a olvidar a Dios y su deber razonable hacia Él.

Solo añadiré mi sincera oración al Dios y Padre de todas las misericordias fieles,
que estas verdades (que he echado en el arca del tesoro), hagan que el lector serio,
de cualquier denominación, se encuentre con la bendición divina.
Si dicha bendición es experimentada,
aunque lo que se ofrece aquí puede considerarse justamente como meros panes de cebada,
el alma hambrienta puede recibir algo de fuerza y refrigerio por ello.

John Griffith

30 del octavo mes, 1764.



