[short="Recomendaciones a los Padres e Hijos"]
== Sección I

[.chapter-subtitle--blurb]
Tiernos Consejos, Advertencias y Recomendaciones a los Padres e Hijos

=== Primero a los padres.

Mucho depende de la educación adecuada de los hijos.
Por tanto,
considero que debo hacer algunas observaciones sobre este
tema conforme al Señor le plazca abrir mi entendimiento,
sin cuya asistencia y bendición en nuestras labores,
estas resultan ser totalmente infructuosas.

El pueblo de Israel estaba estrictamente obligado a hacer que la
educación de sus hijos en la ley de Dios fuera su deber permanente:
"`Oye, Israel: Jehová nuestro Dios, Jehová uno es.
Y amarás a Jehová tu Dios de todo tu corazón, y de toda tu alma, y con todas tus fuerzas.
Y estas palabras que yo te mando hoy, estarán sobre tu corazón;
y las repetirás a tus hijos, y hablarás de ellas estando en tu casa,
y andando por el camino, y al acostarte, y cuando te levantes.`"^
footnote:[Deuteronomio 6:4-7]

La confianza que reposa en los padres y en los jefes de familia es extremadamente grande.
Ciertamente, su indispensable deber es llevar (lo más que puedan,
tanto por preceptos como por medio del ejemplo) las
tiernas mentes de sus hijos a la virtud,
como lo dice el apóstol: "`Y vosotros, padres, no provoquéis a ira a vuestros hijos,
sino criadlos en disciplina y amonestación del Señor.`"^
footnote:[Efesios 6:4]
Asimismo, "`instruye al niño en su camino,
y aun cuando fuere viejo no se apartará de él.`"^
footnote:[Proverbios 22:6]

Los padres deben familiarizarse primero con el camino de la Verdad,
y con la disciplina y la amonestación del Señor en ellos mismos,
antes de poder instruir a sus hijos en ello.
Lo que probablemente tenga mayor influencia en sus tiernas mentes,
es el ejemplo constante y cuidadoso de sus padres en una conducta abnegada,
lo cual engendrará pensamientos reverentes y honorables en los hijos concernientes
a aquellos que la Providencia ha puesto sobre ellos.

Los padres deben procurar demostrarles a sus hijos que ellos prefieren
que busquen una herencia celestial por encima de la terrenal;
y que sus almas sean adornadas con la gracia del Espíritu Santo,
y que no sólo sus cuerpos sean adornados con atavíos externos.

Es muy probable que los niños valoren lo que ven que sus padres prefieren,
ya sean las cosas del mundo, o las cosas de Dios.
Si este es el caso (que considero que todas las personas sensatas reconocerán), entonces,
¡cuánto depende de ellos para la promoción de la verdad y la justicia en la tierra,
tanto en lo que respecta al tiempo presente, como en las generaciones venideras!
Esto se muestra claramente en el testimonio del Señor sobre Abraham; "`Y Jehová dijo:
¿Encubriré yo a Abraham lo que voy a hacer,
habiendo de ser Abraham una nación grande y fuerte,
y habiendo de ser benditas en él todas las naciones de la tierra?
Porque yo sé que mandará a sus hijos y a su casa después de sí,
que guarden el camino de Jehová, haciendo justicia y juicio,
para que haga venir Jehová sobre Abraham lo que ha hablado acerca de él.`"^
footnote:[Génesis 18:17-19]
La preocupación piadosa de Abraham parece ser ferviente,
incluso para el hijo de la sierva; donde le dijo al Señor:
"`Ojalá Ismael viva delante de ti.`"^
footnote:[Génesis 17:18]

Los esfuerzos constantes y fieles,
con clamores secretos hacia Dios para que Su bendición los alcance,
pueden resultar eficaces para la preservación de los hijos.
Este cuidado debe comenzar muy temprano,
incluso tan pronto como sean capaces de distinguir
lo que les complace y disgusta a sus padres.
Muy pronto se puede notar una voluntad egoísta y obstinada en los niños,
la cual es muy propensa a buscar su propio camino,
antes de que puedan juzgar lo que es mejor para ellos.
Esta voluntad debe ser sometida constantemente a aquellos quienes deben juzgar por ellos.
A los niños nunca se les debe permitir
conseguir lo que quieren a través de un temperamento demandante e irritable,
ni siquiera cuando lo que desean sea apropiado para ellos,
lo cual podrían recibir si estuvieran en una actitud sumisa.
De esta manera, verán rápida y claramente,
que es más beneficioso y cómodo para ellos someterse completamente a sus proveedores,
y que nada se puede conseguir a través de una actitud egoísta y obstinada.
Esto debe llevarse a cabo mediante una mano firme y constante,
que facilitará en gran medida el trabajo de los padres en el gobierno de sus hijos,
y que puede resultarles de gran beneficio, quizás a través de todo el curso de sus vidas;
ya que, al aplastar la voluntad egoísta y terca de sus niños en sus primeros brotes,
podría así morir, y nunca más obtener la preeminencia.
Esto sería una gran bendición,
y ellos tendrían más razones para agradecer a sus vigilantes padres
por suprimir este y otros brotes perjudiciales en ellos,
que por recibir una gran herencia externa.
En verdad,
todo lo que sea de una naturaleza maligna debe mantenerse
sometido en los niños a través de medios cuidadosos y constantes.
¡Oh, qué generación de jóvenes más esperanzadora tendríamos,
si los padres en general ejercieran este prudente cuidado en todas las cosas!
Verdaderamente creo,
que en lugar de que los jóvenes sobrios y virtuosos
sean como "`pájaros solitarios sobre un tejado`"^
footnote:[Salmo 102:7], los rebeldes,
desobedientes y obstinados lo serían y esto traería juicio sobre ellos.

El cuidadoso cumplimiento de este gran deber traería una gran recompensa a esos
padres que no tienen mayor alegría que ver a sus hijos caminando en la Verdad.
Y aunque los padres no tengan éxito, como ha sucedido algunas veces,
estarán limpios de la sangre de sus hijos ante la vista de Dios,
lo cual es algo muy grande; de modo que,
aunque la rebelión y mala conducta de sus hijos pueda ser su aflicción,
no será su pecado.

A veces me sentía muy afligido,
cuando veía a jóvenes en el camino de la ruina por la indulgencia imprudente
de sus padres (especialmente las madres) haciéndose a sí mismos y a otros,
simples esclavos de los deseos perversos de sus hijos.
Estos se esmeran por extinguir la llama de las actitudes problemáticas
de sus hijos con métodos que solo añaden combustible al fuego;
cambiando el orden de la naturaleza, al someterse a los que deberían someterse a ellos.
Y al responder a sus antojos irracionales,
se generan más trabajo de una naturaleza desagradable.
Los padres que son así de imprudentes tienen pocas razones para
criticar a sus hijos por querer hacer siempre lo que quieren,
y no estar sujetos a ellos cuando crecen, porque ellos mismos han fomentado,
alimentado y apoyado esa actitud egoísta en ellos desde sus cunas.
Y a menos que le permitan al Espíritu de Dios apoderarse profundamente de ellos,
y cambiarles el estado de sus mentes,
serán incapaces de brindar consuelo ya sea a ellos mismos o a otros,
al no haber sido formados para ser buenos sirvientes, esposos,
esposas o miembros de la sociedad.

¡Ay!,
cuando miro al mundo y reflexiono en cómo se revuelca en la abundancia de maldad y corrupción--que
posee la humanidad como una especie de sucesión de padres a hijos,
como las herencias externas--no tengo suficientes palabras
para exponer en su totalidad tan deplorable caso.
¡Qué doloroso es observar incluso a niños (por el poder del ejemplo) ser como adultos
en cuanto a la maldad y la dureza de corazón! La costumbre y la práctica habitual han
cambiado de tal manera la opinión común que había sobre algunos terribles males,
que ahora parece haber muy poco remordimiento en la casi constante práctica de ellos.
Muchos niños son criados (como lo fueron sus padres) siendo ajenos
al deber que tienen tanto hacia Dios como hacia el hombre.
Esta casi universal infección de maldad,
olvido de Dios y revuelco en las contaminaciones de este mundo, son muy alarmantes,
y piden a gritos una reforma, no sea que el Señor quebrante con juicio las naciones,
como corriente impetuosa.
De hecho, es una tarea dolorosa para padres piadosos,
criar a sus hijos (en medio de una depravación tan general) sin que reciban alguna
mancha de esta contaminación que corre en nuestros días como un torrente fuerte.
La manera más segura de hacerlo es que los padres (de forma muy
estricta y firme) los mantengan lejos de este tipo de compañía,
aunque sea muy inconveniente en varios aspectos externos.
Pero ¡oh!, el alma es la parte más preciosa de ellos, y los padres,
por encima de cualquier otra consideración,
deben preocuparse en preservarla sin mancha de las corrupciones de este mundo.

En esta importante tarea, no hay mejor regla por la que debamos vivir,
que la perfecta sumisión al Espíritu de Verdad,
que ha prometido guiarnos a toda la Verdad.
Si Le prestamos atención,
no consentiremos a nuestros hijos en nada contra lo que el Espíritu testifique en nosotros.
Y estaremos lejos de alegar que, por ser jóvenes,
algunas libertades más grandes se les pueden conceder en esto o en aquello.
Más bien, sentiremos que, como son parte de nosotros mismos,
la misma ley divina debe ser la regla para ambos, tanto para ellos como para nosotros.

He notado que algunos padres,
que parecen haber aprendido (en cierto grado) la lección de la humildad
y la abnegación (hasta donde se puede descubrir por su apariencia externa),
no solo dejan que sus hijos vivan de una manera completamente diferente,
sino que incluso están dispuestos a introducirlos
(desde muy jóvenes) en cosas vanas y mundanas,
manifestando claramente que se sienten orgullosos de verlos así. Estos padres,
a pesar de su apariencia externa,
muestran gran insensatez y manifiestan que no son
realmente lo que quieren que los demás crean de ellos.
Deseo sinceramente que los padres--los que consienten
libertades inapropiadas en sus hijos,
al permitirles desviarse de esa simplicidad y abnegación pura a la que la Verdad lleva
a todos los que la siguen--consideren el daño que sufren sus hijos por ello,
siendo puestos en una variedad de situaciones difíciles
y peligrosas con respecto a las tentaciones.
De hecho, los inconscientes adolescentes,
a través de su tendencia a desear las cosas más atractivas del mundo,
y la indulgencia de sus padres imprudentes en estas cosas, están, por así decirlo,
preparados para la ruina, a menos que la misericordia divina se interponga.
Algunos padres han sido traspasados de muchos dolores a causa de esto,
y han tenido grandes motivos para arrepentirse cuando ya era demasiado tarde;
y hay razones para temer que la sangre de sus hijos será requerida de sus manos.

Algunos quizás piensen que soy muy fuerte y severo con los padres,
insistiendo en que no siempre es su culpa cuando los hijos persiguen cosas equivocadas.
Esto ya lo he reconocido, y es cierto que con frecuencia son muy tercos y rebeldes.
Tal argumento es válido cuando los hijos están en
edad de convertirse en sus propios gobernantes,
y tienen la capacidad de proveerse de ropa y sustentarse por sí mismos.
Sin embargo, creo que el argumento es irrelevante cuando sus padres proveen para ellos,
quienes no sólo tienen poder para aconsejar y persuadir,
sino también para ordenar y restringir.
Aquí, un padre ciertamente puede y debe mantener autoridad absoluta,
especialmente en los casos donde el testimonio de la Verdad está en peligro de sufrir.

Es muy evidente que Elí fue grandemente culpado por no haber reprimido a sus hijos malvados,
a pesar de que se muestra claramente que él desaprobaba sus prácticas,
discutía con ellos al respecto,
y puso delante de ellos las consecuencias mortales de su mala conducta.
¡Cuán conmovedor es considerar las temibles calamidades que cayeron sobre esa casa,
y también sobre Israel, probablemente en alguna medida por el mismo motivo!

La negligente e imprudente indulgencia de los padres al criar a
sus hijos resulta también en una pérdida dolorosa para la iglesia,
ya que la consecuencia de ello tiende a obstruir grandemente el progreso de la Verdad,
siendo una piedra de tropiezo en el camino de los que buscan seriamente.
Cuando las personas del mundo ven que las libertades indebidas
de las que son llamados a salir son permitidas entre nosotros,
se ven ofendidos.
¡Oh!, como quisiera que los padres, los hijos y todos los que son infieles,
y permiten fácilmente que las diversas ramas de nuestro testimonio cristiano caigan,
consideraran profundamente la lamentable consecuencia
de esto al estorbar el progreso de la Verdad,
y eclipsar terriblemente la belleza de Sion.
Porque tengo gran esperanza de que entonces prevalecería
un celo más vivo y un fervor santo,
y que los hijos e hijas descuidados se levantarían,
y se sacudirían el polvo de la tierra,
y se vestirían con la ropa hermosa de santidad y Verdad,
para que Sion se vuelva cada vez más una alabanza en la tierra.

=== Ahora para los hijos

Después de haber ofrecido algunas observaciones con
respecto al importante deber de los padres,
ahora queda hacer lo mismo respecto al indispensable deber
de los hijos de honrar y obedecer a sus padres en el Señor.
Esto es algo que las Sagradas Escrituras ordenan estrictamente,
y es una obligación permanente e indispensable.

El mandamiento dice: "`Honra a tu padre y a tu madre, para que te vaya bien,
y seas de larga vida sobre la tierra.`"
Lean Mateo 15:4, Marcos 8:10, Lucas 18:20,
Efesios 6:2-3. En esas cosas que son conforme a la ley de Dios,
ningún hijo puede quedar absuelto ante el Juez supremo
al desobedecer o deshonrar a sus padres.
Esta obediencia y honor no solo exigen someterse a lo que demandan u ordenan,
sino también preservar un respeto reverente y un
cariño honorable en el corazón (que surgen del amor),
que en todas las debidas ocasiones los animarían y protegerían.
Es un pecado grave desobedecer y despreciar a los padres,
tal como aparece en Deuteronomio 27:16:
"`Maldito el que deshonrare a su padre o a su madre;`" y en Proverbios 30:17:
"`El ojo que escarnece a su padre y menosprecia la enseñanza de la madre,
los cuervos de la cañada lo saquen y lo devoren los hijos del águila.`"
"`Oye a tu padre, a aquel que te engendró; y cuando tu madre envejeciere,
no la menosprecies,`" etc.
(Proverbios 23:22).

Por otro lado,
es muy evidente cómo la benevolente y vigilante Providencia
siempre estuvo con los que temían al Señor,
y con los que amaban, honraban y obedecían a sus padres; como Jacob, José, Rut,
Samuel y David;
también los recabitas (Jeremías 35). Este escrito se extendería más allá de mi intención
si mencionara todos los excelentes modelos y ejemplos con los que hemos sido favorecidos,
los cuales son adecuados para instruir, animar y favorecer a la juventud,
así como a todos.

Estar familiarizado con esos escritos sagrados, es algo muy recomendable y provechoso.
Recuerden lo que Pablo dijo de Timoteo, su hijo amado:
"`Desde la niñez has sabido las Sagradas Escrituras,
las cuales te pueden hacer sabio para la salvación por la fe que
es en Cristo Jesús. Toda la Escritura es inspirada por Dios,
y útil para enseñar, para redargüir, para corregir, para instruir en justicia,
a fin de que el hombre de Dios sea perfecto,
enteramente preparado para toda buena obra`" (2 Timoteo 3:15-17). Pero que todos consideren,
que el beneficio de la salvación por medio de las
Sagradas Escrituras depende completamente de la santa,
viva y poderosa fe de Cristo, que obra por amor,
purificando el corazón. Es por medio de ella que llegamos a ver a Aquel que es invisible,
y consecuentemente a entender los preciosos misterios de Su reino,
en la medida en que sea apropiado y necesario para nosotros
que los conozcamos (que es todo lo que nos es lícito desear).
Existen muchos otros libros buenos y provechosos,
pero ninguno que contenga tal almacén de ricos tesoros y sublimes misterios celestiales,
hermosamente envueltos y encubiertos de la sabiduría terrenal y del entendimiento carnal.
Porque nadie puede conocer las cosas de Dios, sin la asistencia de Su Espíritu,
como se muestra en 1 Corintios 2:10-15, y en muchos otros textos.

Entre los espiritualmente vivos en la iglesia (como
se muestra en las frecuentes e importantes advertencias,
exhortaciones y consejos a la juventud),
ha habido un gran interés de que las personas lean tanto
las Sagradas Escrituras y otros libros beneficiosos,
como también que se abstengan cuidadosamente de todos los demás
libros que tienden a sacar la mente del temor santo de Dios,
y de un estilo de vida sobrio y virtuoso,
o de aquellos que son escritos solo para entretener, siendo totalmente infructuosos.
El tiempo es muy precioso, corto e incierto; por lo tanto,
debe ser redimido cuidadosamente para el beneficio del alma inmortal.
Además,
la juventud debería aprender a temprana edad a someterse al Monitor
divino e interno mediante una obediencia estricta y cuidadosa,
como también a sus padres y a todos los que tienen autoridad sobre ellos,
evitando cuidadosamente los entretenimientos vanos e improductivos,
como también la conducta corrupta del mundo.
Les aconsejo encarecidamente a todos,
que eviten cualquier cosa (tanto en la vestimenta como en el discurso)
que pueda tener la menor tendencia de llevarlos a una unión o amistad
con "`los hijos de la tierra,`" o con el depravado y degenerado mundo
que se revuelca en la contaminación y en grandes perversiones,
para que no sean apartados y amancillados como sucedió con Dina,
al salir a ver a las hijas del país (ver Génesis 34),
y como sucedió con los hijos de Israel,
cuando lamentablemente se allegaron a las hijas de Moab
y Madián. Y no olviden la terrible caída de Salomón,
el rey más sabio,
que por unirse íntimamente con aquellas que eran ajenas a Dios y a Su pacto santo,
su corazón se apartó del Dios viviente y verdadero,
rebajándose tanto que se inclinó ante sus viles ídolos mudos.
El tiempo no es suficiente para recapitular los casos
lamentables registrados en las Sagradas Escrituras,
y en otros relatos auténticos,
relativos a las consecuencias perjudiciales que tuvo el
pueblo de Dios al mezclarse y unirse con las naciones.
Su seguridad está en apartarse y morar solos, porque Él dice:
"`Salid de en medio de ellos, y apartaos, dice el Señor, y no toquéis lo inmundo;
y yo os recibiré`" (2 Corintios 6:17).

Nuestra juventud^
footnote:[Habla de la juventud dentro de la Sociedad de Amigos.]
ha sido favorecida con un ministerio vivo y poderoso que
a menudo ha alcanzado al testigo de Dios en sus corazones.
Qué gran ventaja es esto cuando consideramos que la mayor parte de la
cristiandad (casi desde los días de los apóstoles) se ha privado de esto,
habiéndolo sustituido con la sabiduría y el aprendizaje humano.
Por esta razón,
las almas jadeantes y sedientas entre ella no han podido recibir
más de sus ministros que las turbias aguas de Babilonia.
En realidad,
estos ministros no han podido dirigir los corazones
hambrientos a los pastos del rebaño de Cristo;
más bien, han oscurecido el consejo con una multitud de palabras sin sabiduría,
e invalidado los mandamientos de Dios con preceptos,
invenciones y tradiciones de los hombres.
¡Qué bendito tiempo es este en el que les ha tocado vivir!; sí,
un tiempo en el que la luz evangélica y la verdad
se han manifestado a sí mismas en perfecta pureza.
¡Oh, que nuestra juventud considere y medite profundamente en sus corazones,
que a pesar de los grandes y fervientes esfuerzos hechos en amor y en celo piadoso
por la preservación de la Sociedad en el camino de la verdad y la justicia,
aun así,
ha sido muy lamentable y evidente la decadencia espiritual
en las vidas de muchos entre nosotros!
Una lamentable cantidad de indebidas libertades nos ha inundado;
muchos han aumentado terriblemente su entrega a esos placeres corruptos y perecederos,
y a esos pasatiempos superficiales,
que nuestros predecesores (verdaderamente piadosos)
negaron por completo y le dieron la espalda,
dejándonos testimonios abundantes y vivos, a modo de advertencia y precaución,
para evitar cuidadosamente que nos enredáramos con estos yugos de esclavitud.
Estas cosas han prevalecido al no permanecer en el temor de Dios,
y al no considerar debidamente que Él siempre está presente,
mirando todas nuestras palabras y acciones,
aunque estén totalmente ocultas a la vista de los mortales.
Cuando la mente se vuelve a Su Testigo puro en el corazón, encontramos reprensión,
corrección y juicio, al haberles dado lugar a cosas inapropiadas;
y mientras los jóvenes permanezcan sujetos a esto,
tendrán temor de transgredir Su ley pura en el corazón,
ley que encontrarán que concuerda exactamente con los preceptos y mandatos
registrados en las Escrituras con respecto a su deber con Dios,
con sus padres y con toda la humanidad.

La razón por la que muchos de los que ven su deber, fallan en el cumplimiento de este,
es debido a que se han apartado de "`la perfecta ley,
la de la libertad,`" o de la "`ley del Espíritu de vida`" en sus corazones.
Ellos pueden ser informados sobre su deber por medios y leyes externos,
pero la capacidad para cumplirlos surge únicamente desde la ley interna,
según Romanos 8:2:
"`Porque la ley del Espíritu de vida en Cristo Jesús
me ha librado de la ley del pecado y de la muerte.`"
En su obediencia y humilde sujeción a esta santa ley,
los jóvenes disfrutarían de esa paz pura,
serenidad celestial y dulce consolación del alma,
que sobrepasa infinitamente todos los tesoros y placeres de la tierra,
y tendrían una esperanza bien fundada de una eternidad feliz.
Es el adversario el que lleva a la dureza de corazón, a la voluntad propia,
y a un estado rebelde de la mente.
Lamentablemente, esto se puede observar en algunos de los jóvenes, quienes,
por sus temperamentos incontrolables,
provocan mucho dolor y ansiedad en sus padres y amigos,
siendo orgullosos con una noción vana de que son más capaces de juzgar
por sí mismos que aquellos que tienen mucha más sabiduría y experiencia.
De esta manera,
muchos (me temo) se han precipitado a la ruina tanto del cuerpo como del alma.

El peligro es muy grande cuando los inexpertos jóvenes
son orgullosos y confiados en sus propias opiniones.
Esto naturalmente los eleva por encima de la instrucción, poniéndolos de esta manera,
lejos de ser verdaderamente útiles, tanto para sí mismos como para otros.
Estos,
a menos que sus corazones sean vueltos misericordiosamente por un poder sobrenatural,
nunca serán aptos para dirigir familias,
o para actuar como miembros de la iglesia de Dios.
Porque a menudo se manifiesta que,
a menos que todos cedan ante sus voluntades y temperamentos
no crucificados (sin importar qué tan irracionales sean),
interrumpirán la paz de la Sociedad y perturbarán su orden puro,
siendo indomables como las "`vacas de Basán.`"^
footnote:[Salmo 22:12]
Y cuando cualquiera de estos asume la forma externa de la religión,
y se vuelve un miembro activo (sin un cambio de corazón),
resulta ser una carga dolorosa para los miembros vivos del cuerpo.

Por lo tanto, con un gran cariño y deseo por el bienestar de la tierna juventud,
les aconsejo y advierto a que cuidadosamente eviten la compañía y comunión
de todos aquellos que (aunque bajo la misma profesión de cristiandad)
desprecian a sus padres y a los que tienen autoridad sobre ellos,
o que pasan por alto o hablan despectivamente de sus superiores,
tanto naturales como espirituales.

El temor del Señor es el principio de la sabiduría y esto
es lo que hace y lo que mantiene el corazón limpio.
Apréndanlo a una tierna edad,
y por medio de él serán enseñados a acordarse de su Creador en los días de su juventud;
y (conforme al mandato de nuestro bendito Señor), encontrarán que,
al buscar primeramente el reino de Dios y Su justicia,
todas las cosas les serán añadidas.
A medida que la sabiduría divina sea buscada y obedecida,
dirigirá sus pasos en el curso de este corto peregrinaje,
en la elección de una ayuda idónea, y en todos los demás asuntos de importancia.
La Providencia Vigilante estará sobre ustedes cuidándolos, guiándolos y protegiéndolos,
si ponen su mirada en Él y viven en Su temor.

Les conviene seguir con gran diligencia las huellas de los compañeros de Cristo,
que caminaron con Él a través de muchas tribulaciones,
habiendo lavado y emblanquecido sus ropas en la sangre del Cordero.
Estén verdaderamente contentos con esa senda de humildad,
pobreza y abnegación en la que ustedes ven que ellos caminaron;
ustedes nunca podrán alterarla o mejorarla.
Si buscan más libertad de lo que permite este camino, solo les traerá oscuridad,
dolor y aflicción de espíritu.
Lean los escritos de los Amigos de los primeros tiempos,
y observen cuán maravillosamente el poder y amor de Dios estaba con ellos,
y cómo fueron extraordinariamente protegidos en medio de
las furiosas y espumosas olas de los poderes terrenales,
que se confabularon para arrasar con la herencia de Dios.
¡Qué relatos tan alentadores y excelentes han quedado registrados para nosotros,
con respecto a cómo el amor y la vida celestial del Señor
poderosamente cubrían como una sombra sus reuniones religiosas,
y cómo la gloria de Dios resplandecía en medio de ellos!
Esta gloria y poder, a través de la misericordia de Dios, no se ha apartado aún;^
footnote:[Esto fue escrito en 1764.]
aunque se ha retirado en cierta medida.

Estimada y querida juventud,
consideren en su corazón la gran falta de celo que hay en muchas personas; la oscuridad,
la sequedad y la dolorosa confusión,
que se han esparcido sobre nuestras reuniones en este día.
¡Esta condición es realmente difícil de superar,
y muchas veces nos priva de experimentar los lugares
celestiales en Cristo Jesús nuestro Señor!
Estamos en esta condición por nuestra culpa y no por Él,
porque hemos permitido que cosas malas prevalezcan.
¡Oh!,
que nuestra juventud se despierte con un celo piadoso para
clamar al Señor fervientemente como el profeta Eliseo:
"`¿Dónde está Jehová,
el Dios de Elías?`" Y que vele con ardientes deseos de ser empoderada con el mismo Espíritu,
y de suceder a aquellos hombres y mujeres dignos y honorables que han terminado su carrera.
Consideren que su deber diario es seguirlos como una sucesión fiel,
manteniendo el propósito y el testimonio de Dios que les dejaron sus antepasados.
Por lo tanto,
manténganse firmes en la libertad que les ha sido comprada
con grandes sufrimientos y derramamiento de sangre inocente.
Tengan temor de pisotearla,
que es lo que todos ciertamente hacen cuando se alejan de la Verdad tal como fue recibida,
sostenida y declarada por nuestros antepasados.
¡Qué la Verdad sea muy valiosa ante sus ojos de generación en generación,
hasta que el tiempo se acabe!
Aquellos que la desestimen, dándole la espalda,
incumpliendo su testimonio bendito (en sus diversas ramas),
serán seguramente (a menos que se arrepientan) rechazados y echados fuera,
por ser indignos de un honor tan grande como el de llevar
un estandarte de verdad y justicia a las naciones;
y otros serán llamados y escogidos para esa grande y gloriosa obra.
El Señor es capaz de levantar a aquellos que pueden ser comparados con piedras,
y convertirlos en hijos de Abraham,^
footnote:[Mateo 3:9; Lucas 3:8]
por hacer sus obras; mientras que los que podrían haber sido los hijos del reino,
pueden (por su desobediencia) provocarlo a que los excluya.

Concluiré este afectuoso mensaje dirigido a nuestra juventud
con las palabras de Cristo por medio de Juan,
su siervo fiel, a la iglesia de Filadelfia: "`He aquí, yo vengo pronto;
retén lo que tienes, para que ninguno tome tu corona.
Al que venciere, yo lo haré columna en el templo de mi Dios, y nunca más saldrá de allí;
y escribiré sobre él el nombre de mi Dios, y el nombre de la ciudad de mi Dios,
la nueva Jerusalén, la cual desciende del cielo, de mi Dios, y mi nombre nuevo.`"
