== Sección 2

[.chapter-subtitle--blurb]
Observaciones sobre la Naturaleza y Necesidad del Nuevo Nacimiento

La doctrina predicada a Nicodemo por nuestro Señor Jesucristo,
sobre la necesidad de nacer de nuevo, Juan 3:3-8,
y aquella doctrina enseñada por Juan el Bautista referente
al bautismo de Cristo con el Espíritu Santo y el fuego,
(siendo una y la misma en sustancia con lo expuesto por el profeta Malaquías,
bajo las vivas metáforas de un fuego refinador,
un purificador de plata y un jabón de lavadores,
junto con muchos otros pasajes similares de las Sagradas Escrituras),
aunque es de suma importancia que todos la entiendan correctamente y la consideren profundamente,
sigue siendo un tema pasado por alto y descuidado por la mayoría de los cristianos profesantes.
Lo único que puede poner un cimiento estable para la felicidad,
tanto en el tiempo como en la eternidad, es poco considerado por muchos,
al menos no con un deseo verdadero, o con algún grado de seriedad,
salvo que sea para rechazar y evadir la fuerza de ese poder que
los separaría de sus amados deseos y gratificaciones carnales.

Las conjeturas y los sueños de la humanidad sobre este tema,
han sido muchos y excesivamente absurdos, pero todos tienen el mismo propósito:
evitar la cruz, para que el yo corrupto, con todos sus aparentes tesoros y adornos,
pueda ser salvo.
En muchos, este yo se ha sentido más atraído por un tipo de adorno y tesoro religioso,
que por cualquier otro;
y satanás (el sutil espíritu que se disfraza a sí mismo) nunca ha dejado de proporcionarle
muchas tentaciones de este tipo a cualquiera que tenga una inclinación religiosa.
El anticristo, como describe un eminente autor,^
footnote:[i.e. Isaac Pennington.]
puede engendrar en su iglesia una semejanza o imitación
de todo lo que se encuentra en Sion.
¡Oh, entonces,
cuánta necesidad tiene la humanidad de esforzarse por alcanzar la verdadera certeza,
ya que nada puede llevar al alma a un estado más deplorable,
que un error de este tipo en la gran obra de salvación!

Sin embargo,
algunos dudan que sea posible alcanzar aquí tal cosa
como una evidencia indubitable de nuestra adopción,^
footnote:[Griffith no se refiere a la mera creencia de que hemos sido adoptados,
sino a la experiencia del Espíritu de Dios dando testimonio de que nuestros
corazones han sido verdaderamente regenerados y transformados.]
a pesar de que esto es tan abundantemente afirmado en las Sagradas Escrituras.
Esto no es algo de lo que nos debamos asombrar con respecto
a los que están en el estado natural y no renovado;
viendo que el hombre natural, según la doctrina de Pablo,
"`no entiende las cosas que son del Espíritu de Dios, y no las puede entender,
porque se han de discernir espiritualmente.`"^
footnote:[1 Corintios 2:14]
Pero estoy persuadido de que ninguno de los que han
experimentado realmente el nuevo nacimiento,
aún tiene dudas o inquietudes con respecto a esta importante verdad.
Me parece irrazonable suponer que la Infinita Bondad,
que conoce la falibilidad y la gran debilidad del hombre, Su criatura,
deje a alguno (cuyo corazón está completamente dedicado a rendir
obediencia a Su voluntad) bajo un error con respecto a estas cosas,
o ignorante de Su aprobación divina.
Esta evidencia santa en las almas fieles es verdaderamente la piedrecita blanca,
y en ella está escrito un nombre nuevo,
el cual ninguno conoce sino aquellos que lo reciben.
Aquí, en verdad, hay una certeza de que sus nombres están escritos en el cielo,
de donde surge un gozo inefable y glorioso.

Un sentido de la ira de Dios en contra del mal,
crea a menudo impresiones profundas sobre las mentes de muchos, de modo que,
bajo un remordimiento doloroso,
están listos para clamar por misericordia y perdón de sus pecados.
Esta convicción en la mente del hombre, de que ha disgustado a su Creador,
no puede proceder de nada en el hombre excepto del testigo
puro de Dios que Él ha puesto allí. Por lo tanto,
es muy razonable concluir que este mismo Testigo divino,
cuando cumplimos fielmente nuestro deber para con Dios (según nos es manifestado),
grabará nuestras mentes con un sentido dulce de aprobación divina,
conforme a Romanos 8:16; "`El Espíritu mismo da testimonio a nuestro espíritu,
de que somos hijos de Dios.`"
Junto con muchos otros pasajes de las Escrituras de igual relevancia.

Cuando alguien está realmente dispuesto a seguir a Cristo,
debe tener mucho cuidado al emprender su viaje.
Muchos se han echado a perder sobre la rueda del alfarero,
por falta de paciencia para soportar el templado adecuado;
tratando de llegar a ser vasijas útiles antes de que hayan pasado por el proceso necesario.
Esto se debe a la falta de un conocimiento profundo de sí mismos.
Todo lo que es de la voluntad de la criatura,
y de la impaciencia de desear escoger o de actuar por sí misma, debe morir en la cruz,
y luego permanecer en un estado de desolación y vacío bajo las dispensaciones del Señor,
hasta que la Palabra eficaz diga: "`¡Sea la luz!`"
Así el Señor, por Su propio poder,
hace una separación perfecta entre la luz y las tinieblas en el hombre,
como lo hizo en el mundo visible.
Hasta que esto se experimente realmente,
el hombre no estará en condiciones de ser puesto
en la rueda para ser formado en una vasija de honra;
y tiene que haber además un tiempo de ser templado, y de soportar el horno.

Estas maravillosas operaciones, que acabo de apenas mencionar de manera alegórica,
causan una impresión muy profunda y duradera en todos lo que han experimentado
la naturaleza de esa regeneración sin la cual nadie puede ver el reino de Dios.
Cuando alguien llega hasta este punto,
no tendrá necesidad de hacer uso de sueños y conjeturas inciertas
para formar un juicio concerniente a su adopción. El nacimiento
divino que se levanta en ellos clama de manera natural,
"`¡Abba, Padre!`"
Y cuando a Él le place aparecer (por lo que se les enseña a esperar pacientemente),
no tienen duda alguna de haber pasado de muerte a vida,
o de ser trasladados del poder de las tinieblas al reino del Señor Jesucristo,
el cual consiste en "`justicia, paz y gozo en el Espíritu Santo.`"^
footnote:[Romanos 14:17]

El gran peligro de que el hombre sea engañado radica
en las misteriosas operaciones de satanás,
quien tiene una fortaleza en aquellos,
que en el tiempo en que fueron despertados por primera vez por el llamado de Cristo,
no permitieron que Su poder prevaleciera hasta el punto
de hacerlos estar dispuestos a dejar todo por Su causa.
Hay algo en el fuerte espíritu y voluntad del hombre que es extremadamente
reacio a despojarse de sí mismo y convertirse en nada,
y someterse por completo a ser guiado y sustentado por otro.
Esto se debe en parte a la excelencia de su constitución,
y a la grandeza de su entendimiento,
encontrando en sí mismo habilidades naturales capaces de llevar a cabo grandes cosas,
y por lo tanto asume (hasta que sus ojos sean abiertos e iluminados desde lo
alto) que es igualmente capaz de comprender lo relacionado con el mundo venidero.
Por lo tanto, en lugar de cesar por completo de su propia voluntad,
y confiar totalmente en la guía del Espíritu Santo, está muy propenso a estar activo,
imaginando que Dios se complacerá de su diligencia
en hacer lo que ha entendido como deberes religiosos;
tales como orar, cantar, predicar, o procurar unirse a otros en esas actividades;
a menudo expresando sus experiencias, y escuchando las de los demás. Sin embargo,
sería abundantemente más agradable para el Todopoderoso, y más provechoso para él mismo,
poner su boca en el polvo, meditar silenciosamente en su propio corazón,
y quedarse quieto, hasta que al Señor le plazca enviar Su luz y Su Verdad,
para que la pobre criatura indefensa pueda moverse
y actuar desde un sentido verdaderamente espiritual,
con su entendimiento iluminado por Dios.
Porque todo lo que se hace en la religión y en la
adoración sin la guía del Espíritu Santo,
es "`culto voluntario`"^
footnote:[Colosenses 2:23]
e idolatría;
porque si el Espíritu de Cristo no nos mueve y opera en todas las prácticas religiosas,
somos susceptibles a las influencias del espíritu del anticristo.

Algunos quizás, a modo de excusa,
están listos para decir que los que afirman la necesidad de ser influenciados
por el Espíritu de Verdad están llenos de "`fanatismo`" y "`presunción,`"
insistiendo en que no existe tal cosa en nuestro tiempo,
aunque reconocen con facilidad, que así fue en los días de los apóstoles.
Pero estos no pueden dar una buena razón de por qué el poder divino
y la eficacia del Espíritu Santo abandonaría a la iglesia verdadera,
ya que sin duda alguna la humanidad tiene la misma necesidad de siempre,
y la naturaleza de la dispensación de Dios es la misma ahora como lo fue antes.

La prudencia común nos enseña a examinar cuidadosamente la claridad
y la validez de nuestros títulos de propiedad terrenal,
para que podamos estar completamente satisfechos de que no nos engañan
ni nos imponen interpretaciones falsas y afirmaciones engañosas.
¿Debemos preocuparnos menos por lo que es infinitamente más importante; es decir,
nuestro título de una herencia eterna?
El hombre debe estar muy vigilante de su propio corazón,
el cual siempre está propenso a mostrarse parcial consigo mismo, y,
a través de los engaños sutiles de satanás,
a hablarse paz y adularse en una concepción falsa
de que él está en el camino a la felicidad eterna,
cuando en realidad es todo lo contrario.
El criterio con el que se juzga a sí mismo puede ser el mismo que el de aquel fariseo,
que subió al templo a orar, o más bien a recapitular sus supuestos méritos.^
footnote:[Lucas 18:10-14]
A lo mejor se mide a sí mismo por sí mismo,
o al comparar sus principios y conducta en la vida
con los de los demás. Pero en este caso tan importante,
no se debe tomar nada como punto de referencia,
excepto el sello de la aprobación divina impreso en el corazón por el Espíritu Santo;
conforme a Romanos 8:14-16: "`Porque todos los que son guiados por el Espíritu de Dios,
éstos son hijos de Dios.
Pues no habéis recibido el espíritu de esclavitud para estar otra vez en temor,
sino que habéis recibido el espíritu de adopción, por el cual clamamos: ¡Abba, Padre!
El Espíritu mismo da testimonio a nuestro espíritu, de que somos hijos de Dios.`"

Habiendo ofrecido estos consejos a modo de precaución,
para que todos aquellos en cuyas manos caigan puedan examinarse a sí mismos sin parcialidad,
para que no caigan inadvertidamente en un error irreparable
con respecto a la salvación de sus propias almas,
ahora me esforzaré por presentarles, desde mi propia experiencia,
un poco de la naturaleza de ese nuevo nacimiento
sin el cual ninguno puede ver el reino de Dios,
y consecuentemente tampoco puede ser miembro verdadero de Su iglesia.
Porque,
no se puede suponer que una persona no regenerada esté debidamente calificada para realizar
algún deber o servicio religioso en ese reino que ni siquiera puede ver.

Por experiencia he encontrado desde mi niñez,
dos espíritus o semillas que luchan en mí para dominar o gobernar.
He descubierto que son enemigos irreconciliables el uno con el otro;
y que no podía servir a ambos al mismo tiempo.
Me fue dado un entendimiento,
por el cual supe que una de esas semillas era una manifestación
de la fuente todopoderosa e inagotable de la Bondad;
y la otra, que en cierta manera había leudado toda la masa,
era una naturaleza malvada y diabólica.
Por causa de esta levadura corrupta,
tuve una fuerte propensión hacia diversos tipos de maldad; sin embargo,
a menudo sentía al buen Espíritu hiriendo al mal, como un hacha puesta a la raíz de este,
según Mateo 3:10,
para destruir lo que evita que el Heredero de todas las cosas posea Su herencia.
Por mucho tiempo estuve como en una especie de suspenso, sin resolver con cuál unirme;
pero vi que todo dependía de mi determinación, y que tenía todo el poder para escoger.
Por un lado, cuando las visitaciones del Espíritu de Dios estaban sobre mí,
despertándome,
me parecía muy terrible provocar que un Ser omnipotente lleno de bondad
y misericordia inmerecida echara mi alma a la perdición eterna.
Por otro lado (especialmente cuando esas impresiones
celestiales de alguna manera se habían desvanecido),
se sentía como la muerte misma renunciar a todas mis gratificaciones carnales,
y exponerme al escarnio y menosprecio del mundo.
No obstante, con el paso del tiempo, el Señor en Su gracia compasiva,
irrumpió en mi alma, con Sus juicios mezclados con misericordia,
de una manera tan poderosa, que hizo que estuviera dispuesto a rendirme a Él,
viniera la vida o la muerte.
En verdad, en ese entonces, debido al dolor de estos juicios, no tenía otra expectativa,
aparte de que mi frágil cuerpo se hundiera bajo el peso
de la indescriptible angustia que estaba sobre mí,
y que mi alma pecaminosa quedara encerrada en un estado de miseria eterna.
Entonces mi clamor fue (como el de Saulo) con temblor y temor, "`Señor,
¿qué quieres que yo haga?`"^
footnote:[Hechos 9:6]
Entonces no vacilé ni retuve nada,
sino que todo lo que él me pidió lo dejé de buena gana,
siendo esto todo lo que yo podía hacer.
En cuanto a cumplir con los deberes verdaderamente religiosos,
tenía que aprenderlos todos,
a pesar de que había sido educado desde mi infancia (por
padres piadosos) de una manera estrictamente religiosa.
Pero he visto que las mejores ayudas externas,
y los principios religiosos más consistentes, cuando solo son profesados,
no pueden en absoluto enriquecer al alma con gracia celestial.

En una búsqueda cuidadosa del Señor,
percibí claramente que mi deber era vigilar y orar continuamente;
meditar en mi propio corazón, o en el Testigo de Dios allí,
para poder recibir una instrucción y ayuda fresca cuando la necesitara.
Negarme a mí mismo y tomar la cruz diariamente tenía que ser mi ocupación constante;
y mientras lo hacía sentía mucha paz y consuelo interno,
y tenía una esperanza bien fundada de que así encontraría
(en el tiempo del Señor) el cuerpo del pecado tan debilitado,
que el yugo de Cristo se haría fácil, y Su carga ligera.

Para lograr un buen progreso en la vida de la religión,
es necesario (al permanecer en la luz divina) conservar un sentido
claro y distintivo de la diferencia entre la carne y el Espíritu.
Esto no se puede lograr sin un profundo cuidado y
sin mantenerse firmemente esperando en el don divino.
Si el ojo se aparta de esto, queda cegado por las tinieblas,
y entonces el hombre es propenso a ser engañado por una luz falsa,
y por las diversas imitaciones que satanás arrojará en su camino para guiarle e instruirle,
persuadiéndole que todo está bien y correcto.
Ser engañado de este modo y quedar establecido en ello,
es un estado verdaderamente deplorable;
porque es muy poco probable que una persona en este estado
alguna vez sea persuadida a creer que está equivocada;
más bien se burlan frecuentemente de cualquier cosa que parezca contraria a su propia
religión y adoración. Evidentemente este fue el caso de un conjunto de profesantes de
una santidad externa poco común y de gran precisión en lo externo de su religión,
durante el tiempo de la aparición personal de nuestro Salvador sobre la tierra.
Pero, a pesar de todo esto,
estas mismas personas fueron claramente los enemigos
más fervientes que Cristo tuvo entre la humanidad.

Por lo tanto,
viendo que los frágiles mortales son susceptibles de cometer errores tan peligrosos,
¡cuán extremadamente cautelosos y vigilantes deben ser todos! ¡Y qué frecuente
y estricto debe ser el escrutinio que hagan del estado de sus propios corazones,
estado que no puede ser conocido de otro modo sino según al Señor le plazca enviar Su
luz que escudriña el corazón! Esto es un gran favor que sólo reciben los que se apartan
de las tinieblas y están fervientemente interesados en desechar todas sus obras.
Es muy grande el engaño de los que imaginan que toda la obra de regeneración es instantánea.
Esto no puede ser otra cosa que una mentira de satanás, para establecer a las personas,
tan pronto como pueda, en un reposo falso y en un estado de seguridad propia.
¡Oh, cuánto tiempo se requiere para deshacerse de esta naturaleza desobediente,
dura de cerviz y rebelde que nació en Egipto,
antes de que se levante la nueva generación que es apta para entrar en la tierra prometida!

De lo aludido anteriormente, puede entenderse que la buena Semilla o Espíritu Santo,
que surge en nosotros para gobernar sobre la mala semilla,
y que leuda el alma en su propia naturaleza, es en esencia,
el "`nacer de nuevo de agua y del Espíritu,`" o ser "`bautizado con el
Espíritu Santo y fuego,`" o el hombre pasando por la obra del "`fuego
purificador y del jabón de lavadores,`" y siendo purificado como la plata.
Todas estas metáforas significan, de manera muy instructiva,
los diversos tratos del Espíritu Santo,
que puede ser (para el alma dispuesta) como el agua para lavar y bañarse,
y también para beber libremente; y en otras ocasiones, como el fuego purificador,
para purgar la inmundicia y la escoria,
para que el hombre pueda ser tan puro como el oro,
preparado para recibir la imagen y la inscripción del Rey de los cielos; para que así,
dondequiera que vaya, o haga lo que haga, todos lo que tengan sus ojos abiertos,
puedan ver de quien es súbdito.

Es muy notable cómo el profeta Malaquías,
cuando había expuesto la naturaleza del nuevo nacimiento,
se expresa en el cuarto verso del capítulo tercero, de esta manera:
"`Y será grata a Jehová la ofrenda de Judá y de Jerusalén, como en los días pasados,
y como en los años antiguos;`" lo que demuestra claramente como el hombre,
antes de que haya experimentado las operaciones purificadoras y refinadoras antes mencionadas,
está en un estado inaceptable para su Hacedor en sus prácticas religiosas.
¡Que sucederá entonces con aquellos que se han entrometido
en servicios religiosos y entre Sus fieles seguidores,
sin estar vestidos de boda!
Estos gustosamente se harían pasar por Su pueblo,
pero no han caminado por la senda de la regeneración,
ni han pasado por los dolores del nuevo nacimiento.

Cuando el hombre, a través del poderoso predominio del Espíritu Santo,
ha obtenido una buena medida de la victoria sobre el mal,
en su alma abundan evidencias y señales de sus alegres frutos por causa del Señor Jesucristo,
a quien (junto con el Padre, mediante la influencia del Espíritu Santo),
le son ofrecidas como incienso, la alabanza, adoración y acción de gracias.
Tal hombre goza de una abundante corriente de amor celestial
hacia los que son engendrados por el mismo Padre eterno,
conforme a 1 Juan 3:14: "`Nosotros sabemos que hemos pasado de muerte a vida,
en que amamos a los hermanos.`"
Entonces hacer la voluntad de Dios se convierte en su comida y bebida.
Él ve con indiferencia los placeres mundanos cuando los
compara con los gozos e intereses de las cosas espirituales.
Su cuerpo, alma y pertenencias son ofrecidos al gran Dador,
estando entregado a gastar y a ser gastado por la promoción de la Verdad,
según los requerimientos del Señor. Estas particularidades,
y mucho más de lo que puedo exponer,
son el resultado de una obediencia humilde y firme al poder
del Espíritu de Cristo que transforma el corazón,
el cual produce gran paz y consolación celestial,
por el que el verdadero discípulo es animado a perseverar.

¡Oh,
que la humanidad llegara a ver claramente la necesidad tanto
de comenzar en el Espíritu como de caminar en Él,
según el consejo y la práctica de los cristianos primitivos!
Entonces ya no satisfarían los deseos de la carne, porque el espíritu que codicia,
tiene envidia y busca la venganza, sería asesinado.
Las guerras y los pleitos externos naturalmente cesarían;
porque cuando la causa es eliminada, el efecto deja de ser.
Un espíritu egoísta y codicioso,
que busca un beneficio indebido en perjuicio de los demás, sería expulsado,
y entonces tendríamos poder para amar a nuestro prójimo como a nosotros mismos,
y hacer con los demás como queremos que hagan con nosotros.
Todos estos frutos buenos y muchos más,
brotarían naturalmente desde una nueva creación en Cristo Jesús nuestro
Señor. Pero aquellos que no han experimentado este fundamento en sí mismos,
y carecen de las virtudes del Espíritu Santo que
se describen en las Escrituras de la Verdad,
están ciegos y no pueden ver que alcanzar esas sublimes virtudes cristianas
ahora es tan posible como lo fue en los días de los apóstoles.
Así que, las imaginaciones, los sueños,
y las conjeturas abundan entre los cristianos carnales
respecto al método para obtener la salvación,
la cual se experimenta únicamente al nacer desde arriba.
Algunos dicen, ¡miren, aquí está el Cristo!
Otros dicen, ¡miren, allí está! Pero ay, aún evaden la cruz.
De hecho, si no tuvieran que enfrentarse a la cruz,
seguramente abrazarían lo que es correcto,
ya que está tan claramente establecido en las Escrituras.

Las opiniones de muchos, tanto de los católicos como de los protestantes,
sobre la naturaleza de la salvación, son sumamente oscuras y carnales,
haciendo que el rociado de un poco de agua a los recién nacidos (a lo
que llaman bautismo) sea algo esencial para obtener salvación. Por la
manera en que se expresan sobre este tema en su declaración de fe,
pareciera que hacen de esta ceremonia el todo, o lo principal,
de lo que ellos entienden como "`nacer de arriba`"; o por lo menos,
creen que las operaciones del Espíritu para ese fin
están infaliblemente vinculadas al rociado de agua.
Los católicos dicen,
"`Debemos creer que Jesucristo ha instituido en Su iglesia siete sacramentos,
o señales misteriosas y causas instrumentales de la divina gracia en el alma:
el bautismo, como una forma de nuevo nacimiento,
por el cual somos hechos hijos de Dios y limpiados del pecado: la confirmación,
por la cual recibimos al Espíritu Santo por la imposición
de manos de los sucesores de los apóstoles,`" etc.^
footnote:[Manual Católico de Ejercicios Espirituales, página 4.]
La iglesia protestante de Inglaterra, en su confesión de fe dice,:
"`En mi bautismo,`" por el cual ellos se refieren
al rociado de agua sobre los recién nacidos,
"`en el cual fui hecho un miembro de Cristo, un hijo de Dios,
un heredero del reino de los cielos,`" etc.
Después de que un recién nacido es rociado, el sacerdote dice: "`Viendo ahora,
queridos hermanos,
que por el bautismo este niño ha sido regenerado
e injertado en el cuerpo de la iglesia de Cristo,
demos gracias,`" etc.
Y de nuevo, "`Te damos las más sinceras gracias, Padre misericordioso,
por haberte placido regenerar a este recién nacido con Tu Espíritu Santo,
recibirlo como Tu propio hijo por medio de la adopción,
e incorporarlo en Tu iglesia santa,`" etc.^
footnote:[Catecismo y bautismo público de la Iglesia de Inglaterra.]

Estas son claramente puras evasiones.
El hombre odia la muerte del yo,
y prefiere mirar hacia cualquier otra dirección que
no sea la que lo vacíe de todo su amado tesoro.
Sin embargo, si no fuera tan ciego e ignorante en relación con su verdadero interés,
vería fácilmente que su supuesta pérdida daría paso a su más grande ganancia.
Esta lamentable resistencia al verdadero camino ha obligado al hombre a luchar
e inventar para encontrar un camino más fácil hacia el reino de Dios;
un camino que incluye convertirse en heredero de dos reinos,
y servir tanto a Dios como a las riquezas,
aunque nuestro Salvador nos asegura que esto es imposible.

A muchos les encantaría imaginar que el hombre puede ser salvo simplemente
por la "`imputación`" imperceptible de la justicia de Cristo;
lo cual,
si fuera cierto sería una doctrina muy apetecible para una multitud de amantes del yo.
Algunos, que no están de acuerdo con esta opinión,
sino que creen que los hombres deben arrepentirse y experimentar ser limpiados del mal
por "`el Espíritu del juicio y el Espíritu de fuego,`" aún así postergan esta gran obra,
descansando en un tipo de esperanza de que estarán listos
para la felicidad eterna algún tiempo antes de morir.
Estos se apoyan demasiado en la gran misericordia y paciencia del Todopoderoso,
alentándose a sí mismos con la conversión repentina de Pablo y del ladrón en la cruz.
¡Pero qué desconsiderados son esos aplazamientos!
Un dicho de Crisóstomo es digno de mencionar:
"`¡Dios promete misericordia a los pecadores arrepentidos,
pero no les promete que tendrán ni hasta mañana para arrepentirse!`"

Hay otros que imaginan que su regeneración se realiza en un instante;
y para que su engaño sea efectivo,
el falso profeta hace descender fuego (por así decirlo) del cielo ante sus ojos;
y el que es el príncipe de la potestad del aire,
levanta un fervor vehemente y convulsiones en sus pasiones.
A esto lo llaman las obras del Espíritu sobre ellos para su conversión;
e inmediatamente después se crea una especie de cielo falso,
en el que ellos descansan con una aparente seguridad,
suponiendo erróneamente que su llamado y elección están ahora completamente firmes,
y que nunca podrán caer de la gracia salvadora.
¡Oh, qué peligrosa es tal seguridad!

Se podría escribir mucho más sobre los muchos descansos falsos
y los cielos imaginarios a los que los pobres mortales,
siendo engañados (a través de la sutileza de satanás y de
su propia falta de atención) son llevados a descansar;
todo lo cual podría felizmente evitarse si entraran
en el redil de las ovejas por medio Cristo,
la única verdadera puerta y camino al reino eterno,
que se abre para que el alma viaje en él al someterse a Su aparición interna.
Sin duda Él considerará como ladrones y salteadores,
a todos los que entren en Su iglesia por cualquier otro medio.

¡Qué abundancia de rapiña es encontrada en ti oh cristiandad! ¡Oh,
cómo roban el nombre de Cristo, y las experiencias anteriores del pueblo de Dios,
para vivir y también para alimentarse el uno al otro!
¡Qué multitud de pastores enfermizos y estériles,
con rebaños pobres, flacos, hambrientos,
en la mayoría o en todas las sociedades de los cristianos profesantes!
Sí,
es su condición pobre y deficiente (con respecto a la religión)
lo que los induce a estirar su mano para robar.
¿Puede el Dios de justicia y verdad deleitarse en un holocausto hurtado?
No, tales sacrificios son una abominación para Él. Los que han sido regenerados por Él,
aunque a menudo son probados con gran pobreza de espíritu, no se atreven a robar,
porque saben que nada encontrará aceptación con la Bondad Infinita,
sino aquello que sea de Su propio y verdadero nacimiento.
Sí, esto será un olor grato para Él, aunque no sea más que un suspiro o gemido;
que puede ser comparado con la ofrenda aceptable del pobre bajo la ley,
de un par de tórtolas, o dos palominos;
o las dos blancas que la viuda echó en el arca de las ofrendas.
Y aquellos pobres, humildes y dependientes,
quienes han sido hechos hombres honestos por la Semilla
justa y recta que prevalece en ellos,
y que esperan el tiempo del Señor,
estos a menudo son preparados con ofrendas más grandes,
y crecen grandemente con el crecimiento que da Dios.

Para concluir este tema,
resumiré de esta manera la cuestión--el mayor interés del hombre,
al despertar por primera vez del sueño o insensibilidad del pecado,
es entregarse sin resistencia a las manos de su fiel Creador,
para que Él se complazca en obrar en y sobre él tanto el querer como el hacer,
por Su buena voluntad.
Él debe, con el mayor cuidado,
esforzarse por permanecer en ese poder que le permite orar sin cesar,
diciendo "`Venga tu reino.
Hágase tu voluntad, como en el cielo, así también en la tierra.`"
Cuando esta es la inclinación de su corazón,
la gracia de Dios es suficiente protección y defensa en contra
de todos los intentos sutiles de satanás para engañar y seducir.
Los pensamientos más astutos del adversario nunca podrán
prevalecer para arrebatarlo de la mano del Todopoderoso;
y al permanecer allí, es creado nuevamente en Cristo Jesús para buenas obras,
recibiendo sentidos espirituales,
para que pueda ejercitarlos continuamente en el discernimiento del bien y del mal.
Al ser hecho puro su corazón, en un buen grado, por la aspersión de la sangre de Cristo,
su deber constante (mediante la asistencia divina) es preservarlo así,
para que el Señor se complazca en hacer un tabernáculo con él,
y ser hecho para él sabiduría, justificación,
santificación y redención. Estas almas pasivas y rectas reciben
de Él esas cualidades que les permiten colaborar con el Espíritu,
y entender perfectamente el deber pertinente de su día,
tanto como peregrinos y extranjeros en el mundo,
como miembros vivos del cuerpo de Cristo.

