[short="La Naturaleza de la Verdadera Adoración"]
== Sección 3

[.chapter-subtitle--blurb]
La Naturaleza de la Verdadera Adoración.

La naturaleza de la adoración aceptable está claramente establecida
por nuestro Señor y Salvador Jesucristo en unas pocas palabras,
a saber, que debe ser llevada a cabo en espíritu y en verdad.
El motivo de esto es porque "`Dios es Espíritu;`" y, por lo tanto, "`los que le adoran,
en espíritu y en verdad es necesario que adoren.`"
Esta no es la adoración que consistía en ceremonias, tipos y sombras de los judíos,
que fue dispensada a ellos por causa de la debilidad,
sino que es la más excelente adoración de la dispensación del Evangelio,
por la cual el hombre tiene una "`mejor esperanza,`" un acceso más cercano a la Divinidad,
y un mejor entendimiento de sí mismo.
Aquí en el nuevo pacto, aparece tal resplandor de la gloria celestial,
que disipa todas las señales, figuras, y tipos,
y la adoración es llevada a cabo en la verdad,
y en la sustancia real de todo lo que estaba tipificado
y prefigurado por la ley ceremonial de Moisés;
porque la justicia de esa ley se cumple en los que andan y adoran en el Espíritu.

El alma debe inclinarse en absoluta sinceridad,
en humilde postración y con un profundo sentido interno de su propia fragilidad,
carencia, e indignidad,
siendo al mismo tiempo impactada con un sentido vivo de la grandeza
y la digna bondad del Señor. A partir de esta conciencia renovada
en la mente por Aquél que es el único objeto de adoración,
la acción de gracias,
y las alabanzas ascienden debido a Sus abundantes misericordias recibidas,
acompañada de una oración reverente (ya sea en la mente o vocal,
según el alma se sienta influenciada o dirigida por la santa unción) por
la continuidad de Su misericordiosa preservación en el camino de justicia;
según Efesios 6:18: "`orando en todo tiempo con toda oración y súplica en el Espíritu,
y velando en ello con toda perseverancia y súplica por todos los santos.`"

Es claro lo que nuestro Señor manifestó a la mujer de Samaria en Juan capítulo 4,
que la adoración aceptable no está sujeta a ningún lugar, modo, forma,
o ceremonia en particular;
lo cual era un engaño en el que la humanidad en general
había caído y del cual era muy necesario salir,
siendo entonces, así como ahora,
inclinada a complacerse a sí misma y a descansar satisfecha en las prácticas externas.
Si bien algunas de estas sombras externas fueron
dispensadas en condescendencia a los judíos,
estas nunca fueron dadas con la intención de sustituir la adoración espiritual,
ni tampoco fueron en absoluto aceptables sin una humilde inclinación del alma.
Sin embargo, el Señor nos muestra claramente aquí,
que la adoración externa debía ser dejada a un lado,
y que no continuara más en Su gloriosa dispensación espiritual.
Pero difícilmente podría esperarse que una cantidad tan grande
de observaciones externas pudiera ser desechada de una sola vez;
aún así en el tiempo de los días de los apóstoles,
la iglesia fue progresivamente librada de ellas,
como se muestra con las pocas cosas que fueron impuestas
sobre los gentiles (ver Hechos 15:22-29). Pero ¡ay!
La iglesia cristiana (así llamada),
en lugar de abandonarlo todo y volverse puramente espiritual,
fue decayendo gradualmente en cuanto a la vida y el poder,
y ha incrementado en cuanto a las ceremonias y las observaciones externas,
hasta llenarse tanto de ellas como lo estuvo una vez la iglesia judía. Así,
ella obtuvo toda la posesión del atrio externo,
no teniendo nada para disfrutar más que sus propias invenciones,
y nada de qué gloriarse excepto de Babilonia, que había edificado en lugar de Sion,
y así permanecerá, hasta que su medida se llene y su destrucción tome lugar.

Pablo les dijo a los filipenses, "`Porque nosotros somos la circuncisión,
los que en espíritu servimos a Dios y nos gloriamos en Cristo Jesús,
no teniendo confianza en la carne.`"^
footnote:[Filipenses 3:3]
La circuncisión que se refiere aquí, aparece en Romanos 2:28-29 y Colosenses 2:11,
a saber: "`la circuncisión no hecha a mano,
al echar de vosotros el cuerpo pecaminoso carnal.`"
No se requiere de mucha perspicacia para comprobar
que los profesantes del cristianismo en general,
lamentablemente se han apartado de esta clase de adoración.
Y aunque el gran Autor de la religión cristiana ha expresado
tan plenamente Su voluntad y agrado en este punto tan importante,
aún así muchos no se sentirán conformes sin un tipo de adoración,
en el que la parte carnal pueda estar activa,
y sin que haya algo en ella para entretener a los sentidos externos.
Estos buscan adorar al Altísimo con habilidades humanas o con el esfuerzo de sus manos,
y con una devoción indebida hacia las antiguas capillas
católicas y otros lugares de adoración,
llamándolos iglesias, casas de Dios, lugares santos,
etc. Pero tales profesantes de la cristiandad
sostienen una doctrina muy contraria al testimonio de ese santo mártir Esteban,
que dijo: "`Si bien el Altísimo no habita en templos hechos de mano,`"^
footnote:[Hechos 7:48]
y el del gran apóstol de los gentiles, que les dijo a los atenienses,:
"`el Dios que hizo el mundo y todas las cosas que en él hay,
siendo Señor del cielo y de la tierra, no habita en templos hechos por manos humanas,
ni es honrado por manos de hombres, como si necesitase de algo;
pues Él es quien da a todos vida y aliento y todas las cosas.`"^
footnote:[Hechos 17: 24-25]

La mayoría de los protestantes,
aunque se han despojado de muchas supersticiones católicas,
aún conservan algunas ceremonias y observaciones externas que son muy
inadecuadas para la espiritualidad de la dispensación del Evangelio.
Para respaldar estas cosas, ellos no tienen ninguna justificación o autoridad divina,
salvo por unos pocos ejemplos que han reunido del ejemplo de algunos en la iglesia primitiva,
la cual,
habiendo apenas empezado a salir en ese momento de una gran cantidad de ceremonias,
no había sido completa e inmediatamente destetada de todas las cosas de este tipo;
y por esta razón, en condescendencia,
se permitió que algunas sombras externas y ceremonias continuaran por un tiempo.
Porque aunque la iglesia del nuevo pacto tuvo un comienzo tan glorioso,
y estaba tan llena de poder celestial para abrirse paso en el mundo,
sin embargo esto no fue más que el amanecer del día del Evangelio;
y a medida que el Sol de Justicia (que señorea en el día perpetuo
de la salvación de Dios) se levantaba cada vez más y más,
ella debía vestirse de su ropa hermosa para prepararse para el esposo,
y por medio de un incremento gradual de claras revelaciones,
debía crecer en una madurez de sabiduría y juicio.

Nuestro Señor nos alerta con claridad sobre el gran peligro de unir cualquier
cosa de la antigua dispensación ceremonial con la nueva dispensación del Evangelio,
mostrando que de ninguna manera ambas podrían estar de acuerdo,
o subsistir la una con la otra (Ver Mateo 9:17).
La experiencia de muchas generaciones lo confirma.
¡Oh,
cuántas rupturas y cismas ha habido por aferrarse
y defender algunos remiendos del vestido viejo!

Sin embargo, ha habido una lucha piadosa y ardiente por parte de la verdadera iglesia,
incluso a través de las eras más oscuras de la superstición
y la idolatría (aunque oculta de los ojos carnales),
para despojarse de esta pesada y oscura masa de observaciones externas.
Hubo muchos que, por el poder divino, se levantaron en contra de estas cosas,
especialmente en oposición a los errores y las supersticiones más obvios y lamentables.
Pero la más extraordinaria de estas reformas,
en cuanto a su conformidad con la pureza absoluta del Evangelio,
fue a mediados del siglo pasado +++[+++a partir de la década de 1650],
cuando la luz y la verdad del evangelio surgieron
sin la mezcla de ceremonias y observaciones externas.
Y cuando el Señor, por medio de Su poder supremo,
erigió este bendito estandarte de una verdad simple y una
justicia pura +++[+++a través de la antigua Sociedad de los Amigos],
miles de personas acudieron a él y hablaron el lenguaje expresado en Cantares 6:10:
"`Quién es ésta que se muestra como el alba, hermosa como la luna,
esclarecida como el sol, imponente como un ejército con sus banderas?`"^
footnote:[Versión Reina Valera Gómez]
Verdaderamente ellos fueron guerreros "`imponentes`" contra el hombre de pecado,
el hijo de perdición,
siendo poderosos instrumentos en las manos del Señor para revelarlo.
Sí, eran un gran fastidio para los mercaderes de Babilonia,
y para esos que se enriquecían con sus mercancías supersticiosas
que las multitudes compraban por sus adivinaciones y encantamientos.
Estos hijos e hijas de la luz sostuvieron un gran combate de padecimientos;
pero a pesar de todo, con una paciente, pero valiente firmeza,
mantuvieron su postura y salieron victoriosos a través de los sufrimientos,
al igual que el Capitán de su salvación. El eterno Evangelio fue
predicado por ellos con demostración del Espíritu y de gran poder,
y con sustancia como debía ser predicado después de la apostasía: "`Temed a Dios,
y dadle gloria, porque la hora de su juicio ha llegado;
y adorad a aquel que hizo el cielo y la tierra, el mar y las fuentes de las aguas.`"
(Apocalipsis 14:7)

Esto fue, en efecto, una llegada a la sustancia,
después de que los hombres se habían cansado con una abundancia de trabajo humano,
sin haber pescado nada más que vanidad y aflicción de espíritu.
Y para los que reciben este Evangelio (tal y como
se predica según su verdadero propósito y sentido),
no hay manera de evadir la cruz de Cristo,
que es el poder de Dios para la salvación. Aquí no hay cabida
para conservar unas cuantas ceremonias por motivos de apariencia,
pues todos son constreñidos a abrazar la sustancia,
y no se atreven a tocar más los pobres rudimentos,
que fueron tan prostituidos y profanados durante la larga noche de la
apostasía. La virgen hija de Sion está muy segura de que el Esposo de
su alma nunca más se le mostrará en estas cosas inciertas e inmundas,
que han sido y que serán conmovidas en gran manera,
y eventualmente se desvanecerán como un pergamino que se enrolla;
para que queden las cosas inconmovibles.
Según Apocalipsis 21:1; "`Vi un cielo nuevo y una tierra nueva;
porque el primer cielo y la primera tierra pasaron,
y el mar ya no existía más.`" Ya no existía más mar; nada inestable,
fluctuante e incierto; nada de ese elemento de donde la bestia se levanta,
y por lo tanto no queda ningún peligro de que esa
bestia se levante más de allí. Los versículos dos,
tres y cuatro del mismo capítulo,
exponen maravillosamente la gloria de la Nueva Jerusalén descendiendo del cielo,
el tabernáculo de Dios con los hombres, y Dios morando con ellos.
Aquí el Señor enjugará toda lágrima de los ojos de ellos, y no habrá más llanto,
clamor, ni dolor, porque las primeras cosas pasaron.
Ya no hay más mar;
se ha eliminado todo lo que fue la causa de esas espantosas
calamidades y miserias expuestas en esta revelación divina,
al abrir los siete sellos, sonar las siete trompetas,
y derramar las siete copas llenas de la ira de Dios,
quien vive por los siglos de los siglos.
El quinto versículo dice, "`Y el que estaba sentado en el trono dijo: He aquí,
yo hago nuevas todas las cosas.`"
Ahora, no hay nada del vestido viejo, ni del vino añejo,
para romper y quebrar en pedazos el vestido y los odres nuevos.
¡Oh gloriosa hora del Evangelio! ¡Que Jehová de los ejércitos
apresure su obra cada vez más en los reinos de la tierra!

Habiendo ofrecido algunas observaciones generales sobre el estado de las cosas,
ahora queda por hacer algunas observaciones adicionales
sobre ese pueblo que fue extraordinariamente
levantado (como se insinuó anteriormente) en el último siglo,
en este país. Su inicio y primeros comienzos fueron en Inglaterra,
aunque muchos otros territorios también fueron partícipes
del resplandor de la Verdad que estaba surgiendo en ellos;
y puede decirse sin ninguna pretensión,
que a través de ellos se ha propagado (o al menos vislumbrado)
una luz sobre una gran parte de la cristiandad (así llamada),
la cual ha descubierto el misterio oculto de la falsa
iglesia de una forma más clara que antes,
y dado una gran sacudida al largo y continuo reino del anticristo.

Estos, mediante la sabiduría divina,
han sido establecidos como un cuerpo bien unido entre sí,
en medio de quienes permanece el hermoso orden del Evangelio,
que actúa como una cerca que los protege y los preserva del destructor,
manteniéndolos lejos de las contaminaciones de un mundo muy corrompido.
Sin embargo, su preservación depende de que busquen diligentemente,
y esperen única y cuidadosamente por una renovación
diaria de la fuerza y sabiduría de lo alto,
por la cual todas las cosas deben ser dirigidas y organizadas por su seguridad y perseverancia.

A menudo he considerado como un gran favor y bendición que mi suerte
haya sido echada en una época en el que Cristianismo primitivo,
en su poder y pureza, se ha restaurado en el mundo;
y que haya sido tan afortunado de haber nacido y crecido entre el pueblo antes mencionado.
Porque, aunque esto no me hizo un miembro verdadero y vivo de su cuerpo,
aún así me colocó más en el camino de serlo,
que si mi suerte hubiera caído en algunas de las oscuras eras pasadas;
además me ofreció mayores medios de restauración que los que tendría
si hubiera sido educado entre personas supersticiosas y prejuiciosas.
Y verdaderamente, debido a este favor, disfrutado por mí y por muchos otros,
debe haber una respuesta correspondiente de agradecimiento y de obediencia,
o seguramente se sumará a nuestra condena; porque a quien se le ha dado mucho,
mucho se le demandará. Antes de convertirme en un adulto,
fui (a través de la misericordiosa bondad que operaba en
mi alma) llevado a un mejor conocimiento de este pueblo,
y a una mayor familiaridad y comunión (en un sentido espiritual) con ellos,
para mi inefable consolación;
porque encontré que el glorioso Señor era su rey y legislador,
y que Él verdaderamente se había convertido para
ellos en un lugar de ríos y de arroyos muy anchos,
como está escrito: "`Porque Jehová es nuestro juez, Jehová es nuestro legislador,
Jehová es nuestro Rey; Él mismo nos salvará.`"^
footnote:[Isaías 33:22]
Este fue el bendito lenguaje que sonaba dentro de sus fronteras.
Mi espíritu muchas veces se ha inclinado y postrado
reverentemente en un gran temor delante del Señor,
contemplando la hermosa condición y seguridad de este Su pueblo;
del cual he estado listo en decir en un sentido humilde, "`Bienaventurado tú, oh, Israel.
¿Quién como tú, pueblo salvo por Jehová, escudo de tu socorro, y espada de tu triunfo?
Así que tus enemigos serán humillados, tú hollarás sobre sus alturas.`"^
footnote:[Deuteronomio 33:29]

Algunos podrían objetar, diciendo:
lo dicho anteriormente contiene grandes elogios de un pueblo,
entre los que no podemos hallar estas cualidades (en lo externo),
sino que los hemos visto como una sociedad baja y despreciable,
que se esfuerza por hacerse ver extraña e inusual.
Por otra parte,
vemos que muchos entre este pueblo están muy entusiasmados
por el mundo y lo aman como cualquier otro pueblo;
y hay otros que se toman libertades carnales,
y están tan profundamente involucrados en los placeres y festividades de la vida,
y tan ajenos a la abnegación como las personas de otras creencias.
También, cabe señalar que cuando vamos a sus lugares de adoración,
y observamos la forma en que se sientan en silencio,
la tibieza de Laodicea es muy evidente en muchos de ellos,
debido a la condición ligera y despreocupada en que parecen encontrarse (al mismo
tiempo que profesan estar esperando en silencio de cuerpo y quietud de alma para
que la venida del Espíritu Santo renueve sus fuerzas espirituales).
Sin duda,
esto debe ser una burla y un engaño de la índole más despreciable
y provocadora ante la vista del Ojo que todo lo ve.

Ahora, con el fin de explicar un poco la condición del caso,
y responder las objeciones previas,
haré algunas observaciones sobre la decadencia que hay entre nosotros como pueblo,
especialmente en los últimos años,
que ha causado un gran dolor y aflicción a los miembros vivos del cuerpo,
quienes han sufrido dolores de parto para que Cristo sea formado en los que son miembros
de nuestra Sociedad por derecho de nacimiento natural y no espiritual.

En cuanto a la primera parte de la objeción,
puedo decir que este pueblo siempre ha sido visto,
por los profesantes carnales del cristianismo, como un pueblo bajo y despreciable,
incluso desde sus primeros comienzos,
lo que evidencia la misma ceguera y falta de discernimiento que siempre ha privado a
los hijos de este mundo de ver alguna belleza o hermosura en los hijos de la luz.
He mencionado que, aunque fui educado en la misma sociedad religiosa,
no vi que el Señor estuviera entre ellos, hasta que a Él le plació abrirme los ojos,
según Mateo 16:16-17, donde nuestro Señor llama a Pedro bienaventurado,
porque el Padre le había revelado al Hijo.
En otra ocasión les dijo a Sus discípulos, "`Bienaventurados vuestros ojos, porque ven;
y vuestros oídos, porque oyen.`"^
footnote:[Mateo 13:16]
Y es a través de la misma bendición que mis ojos aún permanecen abiertos para ver,
que a pesar de la gran decadencia que prevalece sobre muchos de nosotros,
la gloria no se ha apartado de entre nosotros.
De hecho, los rectos de corazón reconocen que el Rey sigue reinando en Su belleza.
Los príncipes aún gobiernan en el Espíritu de juicio dado a ellos por Dios.
En ocasiones,
mi fe es fortalecida grandemente para creer que nunca dejará de ser así entre este pueblo,
sino que serán preservados como un cuerpo vivo por el poder del Todopoderoso,
a través de todas las generaciones; y que los principios de la Verdad,
tal como ellos los sostienen, se extenderán aún por todos los dominios de la tierra.
Considero que este fue el bendito fin por el que fueron
levantados al principio y sostenidos maravillosamente.
Esta obra gloriosa ha ido en cierto grado avanzando,
a pesar de ser obstaculizada por la infidelidad de muchos entre nosotros,
que (como la mujer necia en Proverbios 14) están derribando (en
alguna medida) lo que la mujer sabia ha edificado ¡Oh que todos
los que confiesen nuestra santa profesión de la Verdad inalterable,
consideren profundamente el peso del compromiso que asumen!

Debido a que desatienden o toman a la ligera esta gran responsabilidad,
descansando en la mera profesión de la verdad,
hemos encontrado que muchos bajo nuestro nombre,
son aún más insensibles y difíciles de ser alcanzados
y despertados por un ministerio vivo y poderoso,
que las personas de otras creencias religiosas.
Esto puede parecer extraño para algunos, pero lamentablemente sé que es verdad,
habiéndolo experimentado con frecuencia en mis labores del Evangelio.
Esto no me es difícil de comprender,
cuando se considera que entre nosotros se han dispensado mayores favores espirituales,
de varios tipos, que entre cualquier otra sociedad de creyentes que conozca,
y esto no se debe a ninguna parcialidad en el Todopoderoso hacia nosotros,
sino que ha sido para capacitarnos para mantener nuestro pacto
con Él en el cumplimiento de la gran obra a la que nos ha llamado.
Cuando alguno es tan desconsiderado como para desatender y despreciar
tales oportunidades de beneficio y de provecho continuos,
se vuelve más duro y obstinado que aquellos que han tenido
menos oportunidad de recibir impresiones celestiales.
La porción de tales (a menos que abracen o acepten
el don de arrepentimiento a tiempo) es muy terrible,
como dice en Proverbios 29:1,
"`El hombre que reprendido endurece la cerviz,
de repente será quebrantado, y no habrá para él medicina.`"
Asimismo, en Hebreos 6:7-8;
"`Porque la tierra que bebe
la lluvia que muchas veces cae sobre ella,
y produce hierba provechosa a aquellos por los cuales es labrada,
recibe bendición de Dios; pero la que produce espinos y abrojos es reprobada,
está próxima a ser maldecida, y su fin es el ser quemada.`"

Verdaderamente la generosidad del cielo para con nosotros como pueblo ha sido grande,
tanto por las influencias y guías consoladoras de
su Santo Espíritu para todos los que las reciben,
como por el abundante fluir del verdadero ministerio evangélico,
que ha sido levantado y mantenido la mayor parte de este último siglo.
Pero ahora, la Sociedad ha sido muy despojada de un ministerio vivo y poderoso;
aunque aún no ha sido (y espero que nunca sea) completamente destituido.
Este ministerio, mediante la bendición divina,
ha sido un medio para reunirnos y preservarnos como pueblo.
Pero muchos entre nosotros se han apoyado y han dependido
demasiado del ministerio externo de otros,
y por lo tanto puede que sea conforme a la Sabiduría divina,
probar cómo se mantendrá la Sociedad sin tanta ayuda externa de este tipo.
A veces pareciera,
como si el Señor deseara volver a Su pueblo aún más hacia lo interno y lo espiritual,
mostrándoles con claridad, que la adoración del Evangelio no depende de medios externos.

Es bastante evidente que la abundancia de predicación, oración, y canto,
no llevan a la mayor parte de la humanidad más cerca del cielo,
ni los hace familiarizarse más con Dios y consigo mismos, que lo que estarían sin eso.
Por lo tanto, se puede decir (y es verdaderamente lamentable),
que estos gastan su dinero en lo que no es pan,
y se entregan a trabajar mucho sin un beneficio real para sí mismos.
Con respecto a nosotros,
el verdadero ministerio ha abundado con pan celestial y con refrescantes corrientes
de agua viva que han fluido a través de los conductos hacia el plantío de Dios;
y aunque muchos no han avanzado, algunos realmente han crecido y florecido.
Pero el Señor de la viña no puede ser limitado a ningún medio en
particular para el socorro y preservación de Su iglesia,
ni siquiera a los que Él ha usado en el pasado.
Tomando en cuenta lo dicho,
me parece algo así como un castigo que tantos valientes
hayan sido removidos a través de la muerte,
y que pocos hayan surgido en el ministerio para sucederlos con el mismo resplandor.
Esto puede resultar ser una gran prueba,
que (a los ojos de los que pueden discernir) hace una clara distinción entre
el simple profesante y el verdadero poseedor de la religión Cristiana.

La manera por la cual el Israel espiritual mora
en su tienda es por medio de una espera silenciosa,
santa y llena de temor, delante del Señor,
donde ninguna adivinación ni agüero puede prevalecer en contra de ella.
Esto es sumamente hermoso;
es algo que alcanza y convence a todos aquellos cuyos
ojos espirituales están en cierto grado abiertos;
como se establece en Números 24:5-7; "`¡Cuán hermosas son tus tiendas, oh Jacob,
Tus habitaciones, oh Israel!
Como arroyos están extendidas, como huertos junto al río,
como áloes plantados por Jehová, como cedros junto a las aguas.
De sus manos destilarán aguas, y su descendencia será en muchas aguas.`"
¡Oh qué consuelo tiene el pueblo elegido por el Señor para
permanecer fiel en esa posición donde Él los ha colocado,
ya sea en silencio o hablando, en el hacer o en el sufrir,
en la prosperidad o en la adversidad!
No hay la menor razón de avergonzarse de la adoración en silencio,
a menos que estemos tan despojados que no tengamos el sentido
correcto de lo que es la verdadera adoración. Entonces,
en efecto es extremadamente despreciable,
y no puede dejar de hacernos aún más repudiables ante los
ojos de la humanidad que los que tienen una forma externa,
decorada con los curiosos inventos y adornos del hombre.
Este estado de insensibilidad a la naturaleza de la verdadera
adoración en los que profesan tener una "`mente espiritual,`"^
footnote:[Romanos 8:6 RV1602 Purificada]
es declarado por el Señor por medio de esta metáfora: "`Si la sal pierde su sabor,
¿con qué será salada?
No sirve más para nada, sino para ser echada fuera y hollada por los hombres.`"^
footnote:[Mateo 5:13]
Por lo tanto,
todos los que profesan la adoración espiritual deberían de temer
grandemente ser encontrados en este terrible estado--a saber,
conservando la forma externa (a la que la Verdad conduce) sin la vida y el poder.

En mis viajes dedicados a la promoción de la Verdad (en casi
todas las áreas del mundo donde existe nuestra sociedad),
he visto y dolorosamente sentido mucho de esta triste ociosidad e insensibilidad,
y eso me ha causado muchos días y noches de lamento, cubierto internamente,
por así decirlo, de cilicio.
He visto que esto sucede por varias razones,
pero principalmente por un afán excesivo en la búsqueda de cosas terrenales;
cosas que son lícitas en sí mismas,
pero cuando la búsqueda de estas cosas ocupa el primer lugar en el corazón,
entonces se convierten en idolatría y se vuelven
el tesoro principal--que sin duda lo son,
cuando el corazón se deleita y piensa en ellas más que en cualquier otra cosa.
¿Es posible que los idólatras adoren al Dios verdadero y
viviente de alguna otra manera que no sea una mera forma?
Este tipo de personas,
se sujetan a las diversas ramas de nuestro testimonio cristiano
únicamente con el fin de conservar una decencia externa,
y mantener la forma y la apariencia ante los ojos de los hombres.
Hay una forma muerta,
insípida e infructuosa de predicación que nunca puede engendrar verdaderamente para Dios,
aunque quizás a veces pueda engendrar en la forma externa.
Pero esto no produce ningún incremento en el pueblo de Dios, excepto de dolor y angustia.
Los evidentes desórdenes y las prácticas inmorales en asuntos en particular,
ciertamente nos han herido y han afectado la causa de la Verdad,
pero no de una manera tan dañina como la de un ministerio sin vida; porque,
dondequiera que se haya preservado el sano juicio
y el espíritu de sana disciplina en la iglesia,
el pecado y los desórdenes han sido juzgados rápidamente y echados fuera del campamento.
Pero, las mayores heridas que hemos recibido han sido en "`la casa de nuestros aparentes amigos,`"^
footnote:[Zacarías 13:6]
debido a sus esfuerzos no santificados de preservar nuestra adoración, ministerio,
y disciplina (o al menos lo que les ha agradado de esto) sólo en la forma externa.
El anticristo siempre ha hecho más estragos en la iglesia disfrazándose de algo creíble,
que por cualquier otro disturbio y oposición directa.

Que se tenga siempre presente lo dicho por Pablo:
"`Pues no es judío el que lo es exteriormente,
ni es la circuncisión la que se hace exteriormente en la carne;
sino que es judío el que lo es en lo interior, y la circuncisión es la del corazón,
en espíritu, no en letra; la alabanza del cual no viene de los hombres, sino de Dios.`"^
footnote:[Romanos 2:28-29]
Creo que nadie negará,
que esto sería igual de veraz si se remplazara la palabra judío por la palabra cristiano.
Si es así, entonces se nos advierte que la forma,
la apariencia y el nombre pueden obtenerse sin experimentar
la obra en el corazón. De hecho,
leemos de algunos "`que tenían apariencia de piedad,
pero sin embargo negaban el poder de ella.`"^
footnote:[2 Timoteo 3:5 RV1602 Purificada]
Quizás éstos no niegan el poder con sus palabras, pero para mí,
la negación más contundente del poder de Dios es vivir y actuar en la
forma externa sin él. Éstos declaran a la humanidad con su conducta (que
habla más fuerte que sus palabras) que no hay necesidad de un poder,
ya que ellos pueden actuar sin él. Y sin duda todos los que aman
desmesuradamente al mundo y las cosas que están en el mundo,
no conocerán el poder de la piedad mientras permanezcan en ese estado;
como dijo el apóstol: "`No améis al mundo, ni las cosas que están en el mundo.
Si alguno ama al mundo, el amor del Padre no está en él.`"^
footnote:[1 Juan 2:15]

Ruego encarecidamente a todos aquellos, a cuyas manos lleguen estas observaciones,
que se detengan y examinen seriamente sus propios corazones sin parcialidad,
para que puedan ver (antes de que sea muy tarde) en qué estado se encuentran.
Si descubrieran (tras un escrutinio riguroso y estricto) que la estructura religiosa,
que algunos llevan muchos años construyendo,
no fue erigida por el mandato y la dirección de la Sabiduría divina,
sería mucho más seguro y prudente dejar que todo sea derribado,
que no quede piedra sobre piedra;
y así poner el fundamento del arrepentimiento de las obras muertas,
y de la fe viva y poderosa en Dios y en nuestro Señor Jesucristo,
en una consciencia purificada por Su sangre.
