== Sección 4

[.chapter-subtitle--blurb]
Observaciones sobre el Ministerio Falso y el Verdadero

El profeta Joel expone de una manera extraordinaria y excelente,
la verdadera fuente del Evangelio en las siguientes palabras:
"`Y después de esto derramaré mi Espíritu sobre toda carne,
y profetizarán vuestros hijos y vuestras hijas.`"
El tipo de profecía de la que se habla aquí, se expresa claramente en 1 Corintios 14:3:
"`Pero el que profetiza habla a los hombres para edificación,
exhortación y consolación.`" De hecho,
una gran parte de este capítulo se enfoca de manera
excelente en exponer el ministerio del Evangelio,
y esa libertad cristiana en la que todos pueden actuar,
según sean llamados debidamente a ello.
Pero debe observarse que tanto las hijas como también los hijos,
según la ley y regla del evangelio, podían ser parte de este ministerio;
que en consecuencia fue permitido y practicado en la iglesia primitiva.
Pero donde el aprendizaje y sabiduría del hombre ha sido
puesto en el lugar del verdadero ministerio del Evangelio,
ha excluido completamente (contrario a esta libertad cristiana) a las mujeres de este.
Qué orgullo y arrogancia deben tener los hombres que excluyen
a todos del ministerio excepto a sí mismos,
a menudo con el fin de obtener ganancias deshonestas, asumiendo el nombre de clérigos,
y llamando a los otros laicos--una distinción que nunca ha existido en
la verdadera iglesia ni ha sido testificada por las Sagradas Escrituras.
Porque las Escrituras dicen, "`Cada uno según el don que ha recibido,
minístrelo a los otros, como buenos administradores de la multiforme gracia de Dios.
Si alguno habla, hable conforme a las palabras de Dios; si alguno ministra,
ministre conforme al poder que Dios da,
para que en todo sea Dios glorificado por Jesucristo.`"^
footnote:[1 Pedro 4:10-11]
. Este es el lenguaje precioso y consolador de la verdad,
y la perfecta libertad del Evangelio que no excluye a nadie que haya recibido un don;
esto es, nadie que haya sido llamado directamente por Dios a ello,
como lo fue Aarón. En Éxodo 28:1 y Crónicas 23:13
se muestra de forma amplia cómo fue llamado Aarón,
y cómo él, junto con sus descendientes,
fueron separados por el nombramiento directo Dios mismo.
La forma en que fueron capacitados,
y cómo debían comportarse en el oficio sacerdotal durante esa dispensación,
también se registraron con esa claridad y puntualidad
que el Todopoderoso siempre usó con Su pobre,
dependiente criatura, cuando le placía ordenar que guardaran cualquier ley o mandamiento.
Por lo tanto, nadie debe recibir nada como una ordenanza de Dios,
a menos que quede indiscutiblemente claro que Dios verdaderamente lo ha requerido;
ni tampoco nadie debe recibir a esos hombres que
han asumido un ministerio sobre sí mismos,
a menos que parezca que tienen más autoridad para esta labor
que han emprendido que el simple hecho de haber sido enseñados
por medios humanos en escuelas y universidades. 
. Pero ¡Ay!
Las autoridades de la tierra permiten que muchos de estos ministros tomen el vellón,
ya sea que verdaderamente alimenten al rebaño o no;
y luego de haber aprendido este oficio,
se muestran tan entusiasmados por sacarle el mayor provecho como cualquier otro.
Su gran desdicha parece ser el resultado de permitir
que el interés personal les ciegue los ojos,
lo que les hace creer que es mucho más ventajoso privar
a la humanidad de recibir "`aquella Luz verdadera,
que alumbra a todo hombre que viene a este mundo,`"^
footnote:[Juan 1:9]
no sea que su comercio se vea amenazado por el surgimiento de esta Luz.
Aquí el ciego guía al ciego, lo que expone a ambos al mayor peligro.
Sin embargo,
estos líderes desprecian y se burlan frecuentemente de aquellos que (por el poder
y el amor de Dios que los constriñe) testifican en contra de su ceguera.
A éstos se le puede aplicar la respuesta que nuestro Señor les dio a los rabinos eruditos:
"`Entonces algunos de los fariseos que estaban con él, al oír esto, le dijeron:
¿Acaso nosotros somos también ciegos?
Jesús les respondió: Si fuerais ciegos, no tendríais pecado; mas ahora, porque decís:
Vemos, vuestro pecado permanece.`"^
footnote:[Juan 9:40-41]
. Cuando los hombres han permitido que el interés personal
los mueva a aceptar un oficio rentable para obtener riquezas,
es común que se encuentren entusiasmados y fervientes en mantenerlo,
y en tratar de suprimir cualquier cosa que se levante en contra de él. Así,
la experiencia de muchas generaciones atestigua,
que desde que la predicación se volvió en un oficio lucrativo,
por el cual se obtiene dinero y honores mundanos,
los clérigos (así llamados) siempre han sido los que más
han promovido que se ejerza fuerza sobre la conciencia,
y persecución contra cualquiera que difiera de ellos en asuntos de la religión;
sin tener ni el más mínimo ejemplo o precepto de
Cristo o de Sus apóstoles para hacer estas cosas.
Todo lo que se les permitía hacer a los ministros de Cristo,
con respecto a los que no los recibían a ellos ni a su doctrina,
era sacudir el polvo de sus pies, como un testimonio en contra de ellos.
Estos habían recibido el don del ministerio de Cristo,
y lo obtuvieron sin dinero y sin costo; porque Su mandato hacia ellos fue:
"`de gracia recibisteis, dad de gracia.`"^
footnote:[Mateo 10:8]
Pero los predicadores asalariados no reciben su ministerio gratuitamente;
alegando que les fue muy costoso capacitarse apropiadamente para ello,
y por eso ahora deben sacar una ganancia de esto,
o terminarán perdiendo su inversión. La franca verdad
es que ellos no reciben su ministerio de Jesucristo;
ni pueden demonstrar que han recibido una comisión divina por el trabajo que se adjudican.
El hecho de que usan las palabras de Cristo y de Sus apóstoles
no les da ninguna autoridad por parte de Él;
porque aún los peores hombres, sí hasta los demonios mismos, pueden hacer lo mismo.
¡Oh, qué lamentable es que pretendan ser enviados por Dios,
como embajadores de Cristo o como sucesores de los apóstoles,
cuando son tan evidentemente diferentes a Él y a ellos,
llevando las marcas de los falsos profetas y asalariados
de los que leemos en las santas Escrituras! 
. Consideremos lo que Pablo, el gran apóstol de los gentiles, dice acerca de este tema;
"`no que seamos suficientes de nosotros mismos para pensar algo como de nosotros mismos,
sino que nuestra suficiencia viene de Dios;
el cual también nos ha hecho ministros suficientes del nuevo testamento; no de la letra,
sino del espíritu; porque la letra mata, mas el espíritu vivifica.`"^
footnote:[2 Corintios 3:5-6 Reina Valera de Gómez]
Esto muestra claramente,
que los ministros en los tiempos del Evangelio deben ministrar
en el vivificante Espíritu de vida y virtud celestial,
según Mateo 28:19-20; "`Por tanto, id, y haced discípulos a todas las naciones,
bautizándolos en el nombre +++[+++literalmente dentro del nombre]
del Padre, y del Hijo,
y del Espíritu Santo... y he aquí yo estoy con vosotros todos los días,
hasta el fin del mundo.`"
Es evidente en muchos pasajes de la Escritura,
que este tipo de enseñanza que bautiza con el Espíritu
Santo fue la que se practicó en la iglesia primitiva;
particularmente en Hechos 10:44; "`Mientras aún hablaba Pedro estas palabras,
el Espíritu Santo cayó sobre todos los que oían la palabra;`" también 11:15-16;
"`Y cuando comencé a hablar, cayó el Espíritu Santo sobre ellos,
como sobre nosotros al principio.
Entonces me acordé de la palabra del Señor, cuando dijo:
Juan ciertamente bautizó en agua, mas vosotros seréis bautizados con el Espíritu Santo.`"
Y viendo que la dispensación de Dios hacia el hombre
es la misma en este tiempo que entonces,
que ahora la humanidad está tan sumergida en el pecado
y alejada de Dios como en aquellos días,
y que el Señor ha prometido estar todos los días
con Sus ministros hasta el fin del mundo,
no hay ninguna buena razón que explique por qué los mismos medios poderosos y eficaces,
no sean ahora tan esencialmente necesarios para la redención del hombre,
como lo fueron en ese tiempo.
Verdaderamente no hay motivo para negar esta verdad.
Y aunque muchos están conscientes de que carecen de la ayuda del Espíritu en su ministerio,
sin embargo, pareciera ser conveniente para ellos, y para conservar su reputación,
persuadir a la humanidad que tal cosa no se puede alcanzar hoy en día. Esto,
junto con muchos otros ejemplos que podrían mencionarse,
muestra claramente que estos no son más que ministros de la letra;
y leemos que este tipo de ministerio solo "`mata`"^
footnote:[2 Corintios 3:5-6]
cuando el Espíritu vivificante no acompaña su predicación. 
. Las distinciones hechas por William Dell en su libro llamado "`Prueba
de Espíritus tanto en Maestros como en Oidores`" sobre los ministros de
la letra y los ministros del Espíritu son muy sabias,
siendo él un hombre letrado,
y bastante familiarizado con el ambiente de la educación universitaria,
al ser un maestro en Gonville y Caius de la universidad de Cambridge.
Haré referencia de algunas de sus citas y también recomendaré al lector tanto este escrito,
como su tratado sobre el bautismo.
. "`Primero, permítame mencionar una objeción. Algunos pueden objetar aquí,
si un hombre predica la palabra en la letra, siendo doctrina buena, correcta y ortodoxa,
no hay duda de que tal hombre debe ser escuchado,
y que puede ser muy beneficioso en la iglesia,
a pesar de que carezca del espíritu de Cristo.
Esto lo he escuchado de muchos que han pensado que han dicho algo.
Pero a estos respondo, que a los que carecen del Espíritu de Cristo,
que es el Espíritu de profecía, aunque prediquen la misma letra de la palabra,
aún así son falsos profetas, y no deben ser escuchados por las ovejas.
Del mismo modo,
los que solamente predican la letra externa de la palabra sin el Espíritu,
hacen todas las cosas de la iglesia algo externo.
En cambio, en el reino verdadero de Cristo, todas las cosas son internas y espirituales,
y toda la religión verdadera de Cristo está escrita en el alma
y en el espíritu del hombre por medio del Espíritu de Dios;
y el creyente es el único libro en el cual Dios Mismo escribe Su Nuevo Pacto.`"
. Además dice, . "`Los que predican la letra externa sin el Espíritu pueden, pese a esto,
seguir viviendo en todos los males internos de la naturaleza corrupta,
y permitirles a otros hacer lo mismo.
Por lo tanto, para concluir, entendamos que esa iglesia que tiene la palabra,
pero carece del Espíritu, es la iglesia del anticristo;
y que ese ministerio que usa la palabra y carece del Espíritu,
es el ministerio del anticristo; y que todas las obras, deberes, oraciones,
predicaciones, ayunos, acciones de gracias, etc., sin el Espíritu de Cristo,
no son nada más que el mismo reino del anticristo, y la abominación desoladora.`"
. Qué importante es para la humanidad,
de cada denominación del cristianismo (tanto la nuestra como las otras),
considerar profundamente estas observaciones en sus corazones, especialmente la última.
Y con respecto a esta declaración de Pablo en Romanos 10:15;
"`¿Y cómo predicarán si no fueren enviados?`", Dell declara lo siguiente:
"`Así que la verdadera predicación, proviene de aquel que es enviado verdaderamente,
y esto nace de la gracia de Dios.`"
No se trata en absoluto de calificaciones otorgadas por las universidades, obispos,
presbíteros, o de cualquier otro hombre o grupos de hombres,
o de los intentos del hombre de intervenir en el
ministerio en su propia voluntad sin el llamado adecuado;
más bien,
depende del poder que constriñe y que proviene de la Palabra
eterna de Dios que impone una necesidad sobre el individuo,
como lo expresó Pablo: "`Pues si anuncio el evangelio, no tengo por qué gloriarme;
porque me es impuesta necesidad;
y ¡ay de mí si no anunciare el evangelio!`" 1 Corintios 9:16
. Es de suma importancia, para la promoción de la verdad y la justicia sobre la tierra,
que el ministerio sea preservado de acuerdo con su institución original, a saber,
bajo la dirección inmediata de la Palabra eterna de Dios, hablando como oráculos de Dios.
En realidad,
el ministerio consiste en que Dios hable por medio
de Sus instrumentos a los hijos de los hombres,
comunicándoles aquellas cosas que Él (que escudriña el corazón) sabe que necesitan;
y al mismo tiempo abriendo sus corazones para recibir la verdad.
Nada más que el amor y poder incomparable de Cristo pueden producir y sostener tal ministerio.
En la naturaleza pura de las cosas,
es imposible que los que son debidamente ejercitados en tal ministerio,
puedan tener intereses egoístas de obtener ganancias temporales por ello.
Dondequiera que esto suceda, podemos estar seguros de que el Señor no los ha enviado;
y por lo tanto no son de provecho alguno para el pueblo.
Y aunque una persona sienta buena voluntad hacia la humanidad,
que fluye del amor de Dios derramado en el corazón,
del que pueden surgir fuertes deseos de hacer bien,
que están libres de cualquier tipo de meta para obtener ganancias,
y aunque se abra ante su vista muchas hermosas doctrinas evangélicas (las
cuales se consideran adecuadas para ayudar y edificar a su prójimo),
aún así todo esto no es motivo suficiente para proceder en la importante obra del ministerio,
sin el llamado y el verdadero don.
Porque,
todo esto puede ser solamente la consecuencia natural de
la operación del amor puro en la mente de cualquier santo,
incluso en aquellos que nunca han recibido un llamado para el ministerio.
. Sin embargo, para algunos, estas benditas operaciones, influencias y revelaciones,
pueden ser dadas para prepararlos para esa obra,
y deben esperar pacientemente bajo la mano formadora
del Alfarero hasta que se cumpla el tiempo.
Esto se verá claramente,
si el ojo se mantiene puro hacia Él. Pero hay grandes motivos para creer que algunos
se han lanzado al ministerio público antes de que se estableciera un verdadero fundamento,
cuando todavía estaban bajo la mano preparadora del Señor,
y así han traído (de manera dolorosa) oscuridad sobre sí mismos,
y algunas veces sobre otros también. Estos,
también han demostrado ser solamente ministros de la letra
(aunque quizás pretendan sentir la inspiración del Espíritu),
y de este modo,
han sido instrumentos de mucha ansiedad y angustia para la iglesia verdadera,
que no puede saborear nada con deleite,
excepto lo que proviene del poder de la Palabra de vida.
Puede ser casi imposible hacer que estos ministros reconozcan el verdadero
juicio de Dios en el actual estado de degeneración de nuestra sociedad,
especialmente cuando tienen una apariencia agradable,
y nada que reprocharles en cuanto a su conducta.
Pero algunas veces ha ocurrido,
que sucede algo que permite exponer su fundamento defectuoso,
aliviando de este modo el dolor de los afectados que se
sientan bajo el viento solano de su ministerio. 
. Personas desconsideradas y débiles se han entrometido en esta gran obra; quienes,
al no esperar debidamente que el juicio del Señor
pruebe sus espíritus y todo lo que surge en sus mentes,
han sido engañados por el enemigo a salir a ministrar en un falso celo,
sin el miedo y temor santo de Dios sobre sus corazones.
Estos se han aprovechado de la libertad del Evangelio que ha sido
restaurada de nuevo entre nosotros (que debe ser preservada,
para que el Espíritu Santo no se apague), a saber,
que todos los que son llamados a la obra del ministerio, ya sea hombre o mujer,
pueden profetizar o predicar uno por uno, para que todos sean edificados. 
. Ha sido un caso doloroso y lamentable para los miembros vivos en algunos lugares,
cuando han visto que tanto lo que algunos dicen como la forma en la que lo dicen,
no podían tener otra tendencia más que la de promoverse a sí mismos,
agobiando de esta forma a la sociedad religiosa,
que les permitió asumir un cargo para el cual no estaban de ninguna manera capacitados.
Ciertamente la iglesia tiene el poder para gobernar y regular a sus propios miembros;
y sin duda tiene el derecho de rechazar por completo un ministerio con el que,
después de ser probado, no tiene unidad.
Además, los verdaderos miembros de la iglesia,
que se han mantenido firmes y tienen una amplia experiencia en los tratos del Señor,
ya sean ministros u otros,
deben ejercer autoridad sobre los que aún no han
demostrado por completo la veracidad de su ministerio,
ni han causado satisfacción al cuerpo en general (aunque se hayan
satisfecho a sí mismos y quizás a algunos otros de poco juicio).
Tampoco nadie debe viajar en la obra del ministerio,
hasta que sepa que hay una satisfacción general con tal ministerio en casa.
Algunos de estos han sido muy confiados y decididos,
duros de ser convencidos de sus errores,
y críticos de esos con una experiencia más profunda,
evidenciando bastante esa señal de depravación expuesta por Isaías 3:5;
"`el joven se levantará contra el anciano, y el villano contra el noble.`"
. En la iglesia de Dios, se debe mantener el buen orden y la decencia,
especialmente entre los principales miembros, para que sirvan como ejemplo para el resto.
La naturaleza del cuerpo de Cristo exige una debida consideración y prioridad a la edad,
los dones, el crecimiento y la experiencia;
los cuales serán cuidadosamente respetados por los que tienen un espíritu recto.
Cuando este no es el caso, es una señal segura de un nacimiento falso,
y una prueba de que ese yo destructivo aún no ha sido asesinado.
Y donde el yo predomina, no falla en mezclarse con todos los oficios religiosos. 
. Ahora, el hecho de que los oyentes tienen el derecho de juzgar,
aparece en 1 Corintios 14:29; "`los profetas hablen dos o tres, y los demás juzguen.`"
Por lo tanto,
es muy presuntuoso para cualquiera tomar sobre sí
el derecho exclusivo tanto de hablar como de juzgar;
o de imponer algo sobre una audiencia o iglesia por el cual no son edificados,
creyendo que no procede de la fuente correcta.
Porque la palabra que se predica no aprovecha,
a menos que esté acompañada de fe en los que la oyen.
Hebreos 4:2. 
. No hay forma de evadir la fuerza y el peso de lo que se mencionó arriba,
a menos que el predicador dé por sentado que los oyentes
en general están tan vacíos de entendimiento espiritual,
que no son capaces de juzgar; lo cual sería muy descortés,
y tendría el sabor de arrogancia.
Estoy plenamente convencido de que,
si el ministerio no alcanza al Testigo divino en los corazones de los oyentes,
y hace que Lo acepten en cierta medida, nunca les será de provecho.
Los verdaderos ministros tienen un testimonio de la autenticidad
de su ministerio incluso en los corazones de los rebeldes;
cuánto más entonces en los de corazón honesto.
. El peligro que surge del estado decadente, adormecido,
e inexperto de muchos en nuestra Sociedad,
me ha impulsado (sintiendo mi mente inclinada en una medida a ello),
a escribir muy abiertamente con respecto a la naturaleza
y a las consecuencias peligrosas de un ministerio falso;
estando completamente persuadido que entre más formales
y superficiales nos volvamos como pueblo,
mayor será el peligro de que tal ministerio surja,
y obtenga el aliento para crecer y prevalecer.
Pues los profesantes sin vida y formales del cristianismo
preferirían tener casi cualquier tipo de ministerio,
que uno en completo silencio.
Por otra parte, un ministerio verdadero no puede fluir libremente, ni ser exaltado,
cuando los oyentes no son más que espíritus mundanos,
vestidos con una forma de religión. Aquí los verdaderos
ministros deben ser como el santo profeta Ezequiel,
donde se dice: "`y haré que se pegue tu lengua a tu paladar, y estarás mudo,
y no serás a ellos varón que reprende; porque son casa rebelde.`"^
footnote:[Ezequiel 3:26]
Y también: "`por tanto, el prudente en tal tiempo calla, porque el tiempo es malo.`"
Amós 5:13
. Aunque estas observaciones acerca de los falsos,
y también presuntuosos y deficientes ministerios, son francas y fuertes,
espero que no causen daño o desánimo a nadie que
se encuentre ocupado en esta importante labor;
y estos comentarios (si se observan con la debida atención),
pueden ser enseñanzas de precaución e instrucción para aquellos a quienes van dirigidas.
Espero que estas observaciones sirvan de aliento a los que están profundamente
agobiados por los que se entrometen en la obra del ministerio sin experiencia
(ya sea por debilidad o por determinación,) para que no sean negligentes
en sus esfuerzos por regular tales cosas mediante un trato directo,
pero con juicio verdadero, amor y ternura, oportunamente aplicado cuando sea necesario.
Esta tarea puede ser algunas veces pesada y desalentadora,
ya que es difícil persuadir a los que han tomado un rumbo equivocado,
e imaginan encontrarse en lo cierto, cuando en la realidad es todo lo contrario.
Lamentablemente, estos han demostrado ser los que tienen más confianza en sí mismos,
ante su supuesta vista y sentido espiritual.
Sin embargo, que el peso de la verdad, que es el más pesado de todos,
sea puesto sobre ellos de vez en cuando,
para que la iglesia no sufra daño y pérdida por alguna
omisión por parte de los miembros vivos.
Se que son aquellos que están vivos en la Verdad, de buen entendimiento y juicio en ella,
y no otros,
los que están calificados para ayudar y dirigir a
los que han perdido su rumbo en un sentido espiritual;
conforme a Gálatas 6:1: "`Hermanos, si alguno fuere sorprendido en alguna falta,
vosotros que sois espirituales, restauradle con espíritu de mansedumbre,
considerándote a ti mismo, no sea que tú también seas tentado.`"
No es el que censura, critica,
o el de sabiduría mundana el que puede restaurar a un hermano;
pues estos no tienen parte en la iglesia de Cristo,
hasta que primero se sometan y ellos mismos sean enseñados por el Señor. . Lo más importante,
en mi opinión,
es tener la capacidad de formar un verdadero juicio
de la fuente o manantial de donde procede el ministerio.
Si brota de la Semilla correcta, originándose de la verdadera Fuente,
entonces se debe proceder con mucha ternura,
y soportar pacientemente la inmadurez o debilidad.
Porque, aunque algunos al principio,
por temor y debido a un profundo sentido del peso de tan importante labor,
pueden tartamudear o comunicarse con considerable dificultad, sin embargo,
la dulce eficacia del poderoso Espíritu vivificante,
(que se siente con ellos en su servicio por los circuncisos de corazón y de oído),
supera con creces la más fina elocuencia sin ella.
Tales, deberían ser alentados con prudencia,
dejándoles tiempo para que encuentren su propio camino.
Sólo hay unos pocos niños espirituales, por muy prometedores que parezcan,
que pueden recibir con seguridad mucho reconocimiento y aplausos.
Un gran daño ha sido causado por esa parte afectiva y apresurada
que se esfuerza por producir ministros antes de tiempo,
e impulsando a otros demasiado rápido,
quienes al principio tenían vida y eran muy prometedores.
Oh, por lo tanto, cuánta prudencia y cuidado debe ejercerse,
para ver claramente en la luz verdadera lo que hay que animar y
lo que hay que desanimar en este asunto tan importante.
